### ISSUE TITLE
Typelevel membership for the delta project

### ISSUE THREAD

**Issue by milessabin** [typelevel/general#1]
+ Delta provides type safe differences for ADTs. 
+ Delta supports the Typelevel code of conduct.

See https://github.com/stacycurl/delta

**Comment by milessabin** [comment]
Tagging @stacycurl.

**Comment by milessabin** [comment]
:+1:

**Comment by milessabin** [comment]
:+1:

**Comment by InTheNow** [comment]
:+1:

**Comment by larsrh** [comment]
@stacycurl, could you please confirm this?

**Comment by stacycurl** [comment]
Confirmed,

Stacy. :)

**Comment by larsrh** [comment]
Perfect! Once the new website is live, I'm going to write down the steps required to add the project to the site, and then we can close this.

**Comment by larsrh** [comment]
Sorry for the delay. PR to add it to the website is pending: typelevel/typelevel.github.com#91.
