### ISSUE TITLE
Submitting Catbird for incubator membership

### ISSUE THREAD

**Issue by travisbrown** [typelevel/general#101]
I started the [Catbird project](https://github.com/travisbrown/catbird) in 2015 to provide instances of Cats's type classes for types from Twitter [Util](https://github.com/twitter/util) and [Finagle](https://github.com/twitter/finagle). It's had eleven (human) contributors, and the `io.catbird` organization currently gets around 20k downloads from Maven Central every month (which is down from a high of 30k per month last summer).

I'm not currently using Finagle or Twitter Util, and the project has fallen a little out of date. It was created before cats-effect existed, and although it includes some cats-effect type class instances, these need attention (see [this PR](https://github.com/travisbrown/catbird/pull/209) or [most of the open issues](https://github.com/travisbrown/catbird/issues)).

It's licensed under the [Apache License, Version 2](https://www.apache.org/licenses/LICENSE-2.0), adopts the Scala code of conduct, generally follows Typelevel-y principles of pure functional programming, has pretty good test coverage via Discipline, etc. I publish new releases approximately every month, usually within a day or two of the monthly Twitter Util and Finagle releases.

[Felix Bruckmeier](https://github.com/felixbr) will be joining the project as another maintainer, so at least I won't be the only one with merging and publishing rights, but in the longer term I think it makes sense for this project to live in the Typelevel organization on GitHub (instead of my personal account), and for its three modules (catbird-util, catbird-effect, and catbird-finagle) to be published to Typelevel coordinates.

**Comment by rossabaker** [comment]
Looks great. I opened https://github.com/typelevel/typelevel.github.com/pull/282, and we can update the URL after the repository is transferred.

**Comment by larsrh** [comment]
Happy to migrate the repository too. Thanks @rossabaker and sorry @travisbrown for the wait.

**Comment by rossabaker** [comment]
And very sorry for the delay.  I opened #103 to discuss how we can manage these better moving forward.

**Comment by travisbrown** [comment]
I dropped the ball on this migration last year, but now that @felixbr and @dangerousben are doing a lot of good work on the Cats Effect 3 migration I think it's time to go ahead and move the repo.

**Comment by rossabaker** [comment]
Do you need any logistical help getting it transferred?  As soon as it's in, we can update the link on the site.

**Comment by travisbrown** [comment]
@rossabaker I don't think so, thanks—I didn't get around to it today, but will move it in the morning.
