### ISSUE TITLE
New project: case-insensitive 

### ISSUE THREAD

**Issue by rossabaker** [typelevel/general#102]
I spun off a [case-insensitive string microlibrary](https://github.com/rossabaker/case-insensitive/) from http4s.  I think Typelevel would be a better long-term home for it.  If there is any interest, I'll transfer the GitHub repo and move the package to `org.typelevel`.

**Comment by alexandru** [comment]
We definitely need something like this 👍

**Comment by larsrh** [comment]
Seems that there is consensus on this. You know the drill (PR to the website, transfer the repo) :wink:
