### ISSUE TITLE
Move jawn-fs2 to Typelevel?

### ISSUE THREAD

**Issue by rossabaker** [typelevel/general#104]
[jawn-fs2](https://github.com/http4s/jawn-fs2) is a small library developed for http4s to support streaming JSON parsing for a variety of JSON libraries.  It lives behind the scenes and is little advertised, so it has not seen much uptake outside http4s.

Since it has nothing to do with HTTP, and is an integration of two Typelevel libraries, we are offering it to the Typelevel organization.  We would transfer the repo into the `typelevel` GitHub org, change the Maven organization to `org.typelevel`, and prefix the root package with `org.typelevel`.

* :rocket: to transfer to Typelevel
* :+1: to make it a Typelevel project, but keep the source and publishing with http4s
* :-1: for neither

**Comment by LukaJCB** [comment]
Seems like we have consensus :) let's transfer to the Typelevel org

**Comment by rossabaker** [comment]
Move is done.  Site update is at https://github.com/typelevel/typelevel.github.com/pull/284. We'll work on republishing and packaging ASAP.
