### ISSUE TITLE
Clarification of definition

### ISSUE THREAD

**Issue by travisbrown** [typelevel/general#105]
I've recently been accused of [harassment](https://twitter.com/runT1ME/status/1263891496953974784) (and ["insanity"](http://archive.is/flG3R), etc.) for [approvingly quoting](https://twitter.com/travisbrown/status/961141834931163136) ([twice](https://twitter.com/travisbrown/status/1014097648238907392)) a woman who wrote the following about two men in the Scala community:

> Believe it: I'm on an active mission to kick guys like these dudes out of our industry completely.

For context, the two men were [joking about the idea of inclusivity and codes of conduct](https://twitter.com/justkelly_ok/status/960796564334829568) at tech conferences (on Twitter, under public accounts clearly associated with their real names).

This happened in 2018, but it's become a kind of rallying point for a group of Scala developers who have claimed that the Twitter threads linked above are ["doxing"](http://archive.is/VS2jn), that they constitute ["threats"](http://archive.is/87usN), that Stew O'Connor and I run an illegal [no-hire list](https://twitter.com/StewOConnor/status/1169206397088583681), and that I shouldn't be [allowed to contribute to Typelevel projects](http://archive.is/YIig6) because of these comments.

Since these particular comments that Kelly Ellis and Stew O'Connor and I made in 2018 have repeatedly been held up as evidence that Typelevel ignores harassment, I think it would be appropriate for the Typelevel leadership to clarify explicitly whether it considers them to be harassment.

**Comment by larsrh** [comment]
Participation in the Typelevel community requires adherence to the [code of conduct](https://typelevel.org/code-of-conduct.html). The steering committee previously reviewed the referenced incident and found no conduct that would prohibit participation. Further commentary on the exchange is out of the scope of the Typelevel organization.

(Side note: the claims of a do-not-hire list were extensively investigated without any evidence emerging.)
