### ISSUE TITLE
Request for access to settings for Typelevel Mouse

### ISSUE THREAD

**Issue by benhutchison** [typelevel/general#107]
I am the creator and maintainer of https://github.com/typelevel/mouse/

I'm doing set up of https://github.com/olafurpg/sbt-ci-release publishing from github actions. Up until now Ive published binaries from my laptop and that's quite a hassle. 

However, I noticed I dont have access to the repository settings, can I be granted access by a Typelevel admin please.

**Comment by larsrh** [comment]
I've upgraded your access, should hopefully work now.
