### ISSUE TITLE
Davenverse component to Typelevel

### ISSUE THREAD

**Issue by ChristopherDavenport** [typelevel/general#108]
Several projects are now anchors for typelevel projects so increasing the bus factor seems a good idea.

- [x] [vault](https://github.com/christopherdavenport/vault) - http4s dependency that provides Request/Response attributes
- [x] [log4cats](https://github.com/christopherdavenport/log4cats) - This has become a fairly widespread logging framework
- [x] [keypool](https://github.com/christopherdavenport/keypool) - The baseline for http4s-ember and rediculous. This is an important project that facilitates a lot of more complex behaviors
- [ ] [cats-scalacheck](https://github.com/christopherdavenport/cats-scalacheck) - The integration library for two other typelevel libraries
- [x] [cats-time](https://github.com/christopherdavenport/cats-time)-  Java Time Instances for cats
- [x] [semigroups](https://github.com/christopherdavenport/semigroups) - Common Semigroup implementations
- [x] [monoids](https://github.com/christopherdavenport/monoids) - Common Monoid Implementations

**Comment by rossabaker** [comment]
> vault, log4cats, keypool

:tada: :tada: :tada:

> cats-scalacheck

Would this be better as a cats module?  Cats repo already depends on Scalacheck.  Is there some circularity?

> cats-time

Are these not in cats due to scala.js?

> semigroups, monoids

I abstain. I haven't studied these.

**Comment by ChristopherDavenport** [comment]
Cats-module I believe would be doable, didn't investigate at the time.

I believe cats-time is not because of js. They substantially increase artifact size on scalajs I believe

**Comment by SethTisue** [comment]
fwiw, vault and log4cats are the ones in the Scala community build, added because I needed to add them. (We can also add things just because we feel like it, of course.)

**Comment by kubukoz** [comment]
How about cats-time built into cats but only in the JVM sources?

**Comment by cquiroz** [comment]
Cats-time in js shouldn't lead to a large size increase, the increase will be seen only on tests

**Comment by rossabaker** [comment]
To restart this, I'm willing to help maintain log4cats, vault, and keypool.  The most urgent tasks there are keeping up with CE3 and Dotty milestones.

**Comment by cquiroz** [comment]
I could help with  `cats-time` to keep it aligned with the js side, and maybe others like `monoids` and `select`

**Comment by ChristopherDavenport** [comment]
Thats everything besides cats-scalacheck which was perhaps be considered instead for a cats module?

**Comment by rossabaker** [comment]
I'm still in favor of cats-scalacheck becoming a module of cats.  Cats is already tightly coupled to its version of scalacheck via the laws.

**Comment by SethTisue** [comment]
it's aliiiiiiiiive https://github.com/davenverse
