### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by rossabaker** [typelevel/general#111]
There's no replacing Lars, but their [open source hiatus](https://lars.hupel.info/articles/oss-hiatus/) has left a handful of projects with lagging maintenance.  This is a tremendous opportunity for new maintainers to step forward.  Responsibilities include:

* Review and merge pull requests.  Many of them are trivial bumps from Scala Steward.
* Respond to issues.  Ask clarifying questions, resolve what you can, solicit help.
* Be mindful of binary compatibility.  If you don't know what this means, let's add MiMa together.
* Tag releases.  Talk to adjacent projects about their needs to schedule them.  If your project doesn't release from CI yet, let's fix that together.
* Adhere to the [Scala Code of Conduct](https://typelevel.org/code-of-conduct.html).  The [admins](https://typelevel.org/code-of-conduct.html#contact) are here to help.

If you're interested in learning the above, but unsure you're ready, we will help you.

The following projects have most recently maintained been carried by Lars.  Please comment if you're interested in keeping any of them going.  Projects that nobody speaks for may be considered candidates for archival:

* [X] simulacrum: (@sh0hei, @vendamere)
* [ ] cats-testkit-scalatest
* [ ] discipline-specs2 (@vasilmkd)
* [X] semigroups (@osleonard, @sh0hei)
* [X] discipline-scalatest (@gagandeepkalra)
* [X] mouse: @danicheg + @BenHutchison
* [ ] simulacrum-scalafix (@vendamere)
* [X] cats-time (@sh0hei, @cquiroz, @lukoyanov)
* [X] monoids (@sh0hei, @danicheg)
* [X] spire (@armanbilge, @cquiroz)
* [X] cats-collections (@gemelen, @lukoyanov, @osleonard)
* [X] frameless: (@cchantep, @pomadchin)
* [ ] claimant

These have one active person, and would benefit from a second.  Much of the recent work is keeping up with dependencies:

* [X] cats-effect-testing (@sh0hei)
* [X] cats-mtl (@sh0hei)
* [X] literally (@sh0hei)
* [X] kind-projector (@danicheg)
* [X] munit-cats-effect (@danicheg)
* [X] scalacheck-effect (@softinio)

**Comment by armanbilge** [comment]
Definitely raising my hand for spire, if you'll have me! And possibly some other projects, depending on other volunteers and whether they are important enough to be spared archival.

**Comment by tpolecat** [comment]
@armanbilge you should talk to @cquiroz about Spire. He has been working on the Scala 3 port.

**Comment by rossabaker** [comment]
Great.  Spire is (probably?) the most starred of these, and I'd love to see it continue strong.  I see @cquiroz has been active lately as well.

**Comment by armanbilge** [comment]
Spire is the library that introduced me to the typelevel ecosystem actually :) Yep, I've been following along with @cquiroz efforts!

**Comment by armanbilge** [comment]
For fun, here's me giving a talk about spire once upon a time ago 😆 
https://twitter.com/ScalaAtTheSea/status/950927583289290752

**Comment by sh0hei** [comment]
@rossabaker I am interested in the maintenance of simulacrum 👍

**Comment by danicheg** [comment]
@rossabaker I'd be happy to help with maintaining `mouse`, I'm in love with `fold` on boolean for years :)

**Comment by gemelen** [comment]
Eager to help with any, most likely `cats-collections` and/or `cats-time`.

**Comment by sh0hei** [comment]
I am also interested in the following maintenance:
- cats-time (because I'm the maintainer of [chronoscala](https://github.com/chronoscala/chronoscala) and cats-time is a project similar to [chronoscala](https://github.com/chronoscala/chronoscala) (We always welcome stargazer to chronoscala 😄 ) )
- semigroups and monoids (because I'm interested in ADT)

**Comment by anicolaspp** [comment]
I wrote most of the original cats-collections data structures along with stew, but it seems that we both are not committed to maintaining it. I hope someone do it and keep it alive.

**Comment by lukoyanov** [comment]
I would be glad to help out with something like `cats-time`  and/or `cats-collections`.

**Comment by osleonard** [comment]
Would be glad to cats-collections & may be semigroups

**Comment by cquiroz** [comment]
I'd like to help on `spire` given my work on the scala 3 port and `cats-time` as it interacts with `Scala-java-time`

**Comment by cquiroz** [comment]
Does `algebra` have maintainers? If not I could help there as well

**Comment by cquiroz** [comment]
Does `algebra` have maintainers? If not I could help there as well

**Comment by cchantep** [comment]
I could try to help on `frameless`

**Comment by pomadchin** [comment]
@rossabaker I'm also interested in keeping frameless up to date. In the most recent work of upgrading https://github.com/locationtech/rasterframes up to the fresh Spark, frameless turned out to be a lifesaver. Cc @cchantep

**Comment by rossabaker** [comment]
Wonderful.  A couple of these projects are quite small and got multiple volunteers.  There's not going to be enough trivial work on all of them, but some are probably ripe for feature work.  There's always more collections, there's always more instances, etc.  Having a partner will be great for reviews.  If you feel redundant on any of these projects, please speak up and we will find you more work!

The projects are on this list because Lars had done the recent work and nobody picked it up since.  Most of them have longtime maintainers who are still around the community.  It would be both polite and wise to try to talk to these people before any major changes:

* simulacrum: @mpilquist
* semigroups: @ChristopherDavenport 
* monoids: @ChristopherDavenport 
* mouse: @BenHutchison
* cats-time: @ChristopherDavenport 
* spire: @DenisRosset. @non is largely retired from OSS, but might still depend heavily on it at work. 
* cats-collections: @anicolaspp cared enough to comment here! :smile:
* frameless: @imarios. Be very cautious about version bumps on this project, because Spark classpaths are hard. Please try to consult with @imarios, as he's been doing it a long time!

**Comment by rossabaker** [comment]
If I tagged you above, but you didn't get a GitHub invite, please ping me.  I was doing a lot at once and the dog has decided to stop sleeping through the night this week. :zzz:

**Comment by rossabaker** [comment]
Since most of you have a partner, I'm not merging anything I see rolling in.  I'm interested to watch new teams and new leaders.  But if anybody wants my review or otherwise gets stuck, please don't hesitate to tag me.

**Comment by rossabaker** [comment]
@cquiroz There's an open PR about folding Algebra into Cats.  It was controversial at the time and I haven't caught up with where it's at, but the answer depends on that resolution.

**Comment by cquiroz** [comment]
Right, I don't really have an opinion about it. I mostly care about `algebra` as requirement for `spire`

**Comment by armanbilge** [comment]
@cquiroz @rossabaker that's my PR actually https://github.com/typelevel/cats/pull/3918, would be really great if it could get merged. I think the controversy is also now on hiatus, unless someone wants to volunteer for that ;)

**Comment by vasilmkd** [comment]
I volunteer to maintain `discipline-specs2`, it is a dependency of Cats Effect.

**Comment by vendamere** [comment]
I volunteer for `simulacrum` and `simulacrum-scalafix`

**Comment by gagandeepkalra** [comment]
@rossabaker I'd love to help out with discipline-scalatest, thanks

**Comment by sh0hei** [comment]
@rossabaker I am also interested in the following maintenance 👍 
- cats-effect-testing
- cats-mtl
- literally

**Comment by softinio** [comment]
@rossabaker I would love to help with ` munit-cats-effect`. Also, I do a lot of spark at work so at some stage wouldn't mind lending a hand in the future with `frameless`.

Caveat is I am relatively new to the Typelevel eco system but keen to ramp up on it so what better than helping here. 

In addition to the above projects I am very experienced with GitHub Actions so any help with the typelevel worlds ci bulid side of things I would love to help.

Thank you for the opportunity.

**Comment by hnaderi** [comment]
I would like to help with `munit-cats-effect`, thanks!

**Comment by rossabaker** [comment]
We already have coverage on `munit-cats-effect` and `frameless`.  I'd love to get some more maintainer coverage on the others that are unchecked above.  Would any of those be appealing?  Of course, as noted above, all of these projects would love to get contributions, where you have specific interests.

@softinio There is a lot of build debt around the ecosystem, so that would be a great place to get involved in general.  There are sbt-spiewak and sbt-davenverse projects that are both excellent for providing batteries-included builds, and I think it would be swell if someone sat them down and reconciled the differences and it resulted in an sbt-typelevel.  A way to make incremental progress would be sbt-github-actions, which is used by both, to replace any lingering Travis CI builds or projects without builds.

**Comment by softinio** [comment]
@rossabaker Definitely down for helping with the build debt around the ecosystem and replacing the ones still using Travis. 

| There are sbt-spiewak and sbt-davenverse projects that are both excellent for providing batteries-included builds, and I think it would be swell if someone sat them down and reconciled the differences and it resulted in an sbt-typelevel. 

Down for that too. Totally my element :-) Excited for this, thanks for the great idea.

Do you have a particular preference with which repo I should start with? 

Else when I get a moment will take a look at all the repos and try to figure out the state of each. 

Thanks!

**Comment by rossabaker** [comment]
It looks like we've done a better job getting off Travis CI than I realized: I can't find any `.travis.yml` files.  I wonder whether there's a way to query for projects _without_ a `.github/workflows/ci.yml`?  And as a second tier, projects whose workflows aren't generated by sbt-github-actions?

The build that most recently caused me pain was kind-projector's, because I had to publish locally.  It has sbt-github-actions already, so progress there would depend on a merger between sbt-spiewak / sbt-davenverse, unless we just picked one for now.

**Comment by armanbilge** [comment]
👍 to an `sbt-typelevel`. It helps a lot with contributing when builds tend to work the same way :)

**Comment by softinio** [comment]
So thinking out loud to work towards an `sbt-typelevel` and to standardize our builds it probably would be useful to as I iterate to test and try new ideas on one single repo. So one thought is I put my hand up to maintain one of the remaining projects with no maintainer and in addition to helping with maintenance I use that as the guinea pig edge build repo to test and to show. 

If you agree with this thought maybe I can help maintain `scalacheck-effect` that seems still available. Will help me learn `cats-effect` as a side effect (pun intended 🤣) too.

**Comment by ixthe0** [comment]
@rossabaker I'd be happy to help with projects that still require maintainers. Unfortunately, I don't have much experience contributing to open source projects, so would be grateful for some initial guidance

**Comment by rossabaker** [comment]
If you're new to contributing at all, I would try submitting a PR before focusing on maintaining a library.  Then you'll be familiar with the process from the other side.  I would take a look at the [good first issues](https://github.com/search?q=org%3Atypelevel+label%3A%22good+first+issue%22+is%3Aopen&type=issues) open in Typelevel and comment on any that catch your eye.  A maintainer should then either assign it to you, or realize it's stale (sometimes we fall behind grooming issues) and politely suggest looking for another one.

Maintainers: the "good first issue" tag is your friend!

**Comment by armanbilge** [comment]
There are many "good first issues" in Cats Effect, this one is begging for a PR! https://github.com/typelevel/cats-effect/issues/587

**Comment by danicheg** [comment]
I am interested in helping with maintaining the `kind-projector` if there are no willing contributors.

**Comment by sh0hei** [comment]
@rossabaker  I am also interested in the following maintenance 👍
- simulacrum-scalafix
- claimant

**Comment by rossabaker** [comment]
@vendamere is already keeping simulacrum-scalafix fresh, but it's nice to have double coverage, especially if either if you start enhancing it.

Claimant had been marked as "no maintenance intended", but you're welcome to revive it if you've got ideas.

**Comment by rossabaker** [comment]
Declaring victory.  We'll handle ongoing calls in individual projects, or broad initiatives in [governance](https://github.com/typelevel/governance).
