### ISSUE TITLE
Request to remove defamatory content

### ISSUE THREAD

**Issue by travisbrown** [typelevel/general#113]
I'm opening this issue to ask the Typelevel admins to delete or close [this issue](https://github.com/typelevel/general/issues/112) opened by @hmemcpy (archived [here](http://archive.today/2021.11.13-081120/https://github.com/typelevel/general/issues/112)), which repeats false and defamatory claims about me.

The people who are making these claims have been asked for clarification or evidence many times, and to my knowledge none has ever been provided. The only concrete action that I'm aware of being accused of is [archiving public comments](http://archive.today/2021.11.15-111316/https://twitter.com/wiemzin/status/1458788007641817093). I have archived tweets and Reddit comments, generally through the use of automated tooling, but there are several reasons these accusations in particular are absurd:

* Public archives like the Wayback Machine automatically index the accounts of hundreds of thousands of Twitter users every day.
* These public archives are open to anonymous use, and it's generally impossible to know who requested a particular snapshot (it's generally not me, or even my scripts).
* There's nothing remotely illegal or unethical about archiving comments made in public, or retrieving content from a public archive, especially when this is done in self-defence.

If the people making these claims believe that they have evidence that I've harassed or stalked anyone, they can submit that evidence to Typelevel or the Scala moderators privately for consideration, or they can share it publicly for others to evaluate, but I don't believe that Typelevel should allow them to spread defamatory rumors on Typelevel's public channels without evidence.

**Comment by robmwalsh** [comment]
Oh please. If you can't take it, stop dishing it out. You're the single most destructive, toxic person in the scala community. Please go write rust (I thought that was your preferred language?) and leave us alone.

**Comment by travisbrown** [comment]
@robmwalsh I know many people don't like that I've criticized Scala community leaders, but I always try to be careful not to accuse anyone of anything that I can't support with evidence, and if something I write is unclear, I try to clarify it. All I'm asking for is the same consideration in return.

**Comment by ChristopherDavenport** [comment]
This issue was removed per CoC section Contact which states

> Send an e-mail to one of the following general moderators if you want to choose who you are talking to:
> 
>  * [Ross A. Baker](mailto:ross@rossabaker.com)
>  * [Christopher Davenport](mailto:chris@chrisdavenport.tech)
>  * [Kailuo Wang](mailto:kailuo.wang@gmail.com)
> 

We will continue this discussion via email.

We acknowledge that not all actions taken have their desired effect and can cause harm to other people whether intentional or otherwise. We ask that everyone refer to encouraged standards of conduct, and ask that members of the community act cognizantly of how their actions in other forums affect others.

> We treat our fellow community members with the empathy, respect and dignity all humans deserve. Keep in mind that public communication is received by many people you don’t know, so before sending a message please ask yourself whether someone from a different context would misunderstand it.

> Always assume good intentions and a willingness to learn, just as you are willing to evolve your own opinion as you gain new insights.

> Don’t just aim to be technically unimpeachable; try to be your best self.
