### ISSUE TITLE
All the sites are 404ing

### ISSUE THREAD

**Issue by armanbilge** [typelevel/general#117]
https://typelevel.org/cats
https://typelevel.org/cats-effect/
https://typelevel.org/cats-collections/
https://typelevel.org/spire/

etc.

**Comment by rossabaker** [comment]
I merged to typelevel.org last night. That would be a prime suspect, but it should have been an innocuous change.

**Comment by armanbilge** [comment]
Seems to be back online, whatever you did :) thanks!

**Comment by rossabaker** [comment]
I renamed the repo to `typelevel.org` because `typelevel.github.com` is a deprecated name that nothing publishes to and describes nothing, but apparently that is a ✨ magic ✨ repo name.  I think `typelevel.github.io` would have worked as well, but I ain't touching it again.
