### ISSUE TITLE
Typelevel membership for Matryoshka

### ISSUE THREAD

**Issue by sellout** [typelevel/general#14]
https://github.com/slamdata/matryoshka

This is a recursion scheme library, strongly FP. It supports the Contributor Covenant code of conduct.

/cc @jdegoes, @tpolecat

**Comment by adelbertc** [comment]
:+1:

**Comment by tpolecat** [comment]
:+1:

**Comment by milessabin** [comment]
:+1:

**Comment by clhodapp** [comment]
If this doesn't belong under Typelevel, I don't know what does :+1:

**Comment by jdegoes** [comment]
:tada:

**Comment by stew** [comment]
:+1:

**Comment by sellout** [comment]
Just noticed the approval label. Does this issue remain open until it has transitioned out of incubator status, or are there just further steps for me to take, or what?

**Comment by larsrh** [comment]
It'll remain open until I add it to the website.

**Comment by larsrh** [comment]
Now on the website: typelevel/typelevel.github.com#97.
