### ISSUE TITLE
Typelevel core/contact group

### ISSUE THREAD

**Issue by milessabin** [typelevel/general#16]
As [discussed](https://github.com/typelevel/general/blob/master/summit-us-2016/governance-panel-notes.md#discussion-about-typelevels-aims-and-purposes-decision-making-process-and-general-constitution) at the Philadelphia summit we expect most decision making to be by consensus and to happen publicly on this github project, via the gitter channel, issues (such as this one) and pull requests. 

We also [recognized](https://github.com/typelevel/general/blob/master/summit-us-2016/governance-panel-notes.md#canshould-typelevel-have-a-group-voice) that there will be (hopefully rare) circumstances where it will be necessary for Typelevel to be contactable and to come to a decision privately and maybe very quickly, before going to a wider forum. Examples of this might relate to a code of conduct violation at a Typelevel event, or on a gitter channel, mailing list etc.; the status of a project as a member of Typelevel in case of a dispute which can't be resolved by consensus; responses to public announcement (eg. the launch of the Scala Center) which we can't discuss publicly because we've been asked to respect confidentiality; discussions with potential sponsors of Typelevel events before they're finalized; and so on.

That being so, we need a somewhat formal list of people who can constitute a group who can be contacted and make an initial judgement on how to proceed. The feeling at the Philadelphia summit is that there is already a de facto list, and that we should make it explicit ... that's the purpose of this issue. 

The consensus at the meeting was that the list should initially include the four people named as contacts on the Typelevel [code of conduct](http://typelevel.org/about), plus the [Cats maintainers](https://github.com/typelevel/cats#maintainers) plus @larsrh (who should really be on the CoC contact list). That makes the list,
- @adelbertc
- @ceedubs
- @fthomas
- @julien-truffaut
- @larsrh 
- @milessabin
- @mpilquist
- @non 
- @rossabaker
- @stew 
- @tpolecat
- @travisbrown

Please note that this is an _initial_ list, and can/will/should change over time. It's pretty clearly not a diverse list, and it's important that we fix that ASAP.

**Comment by non** [comment]
:+1:

**Comment by ceedubs** [comment]
:+1: with the disclaimer that I think people should probably only be on this list if they have explicitly opted in. It's conceivable that someone has become a cats maintainer but doesn't want to be a part of this list.

Consider this me explicitly opting in.

**Comment by travisbrown** [comment]
:+1:

**Comment by stew** [comment]
:+1: I think this is a good list of people, but I can't help but feel this nagging sense that when trying to endorse a set of people like this, that some of the approval needs to come from people not in that set.

**Comment by InTheNow** [comment]
> that some of the approval needs to come from people not in that set.

:+1:  Done :wink:

**Comment by rossabaker** [comment]
The [steering committee](https://github.com/typelevel/governance/blob/main/STEERING-COMMITTEE.md) is formalized in the new Governance repo.
