### ISSUE TITLE
Typelevel membership for http4s

### ISSUE THREAD

**Issue by rossabaker** [typelevel/general#17]
* http4s is a typeful, purely functional HTTP library for client and server applications written in Scala.
* It has a Typelevel-derived [Code of Conduct](http://http4s.org/community/conduct.html).
* The stakeholders are in favor: http4s/http4s#588
* Improved documentation is incubating.

**Comment by fthomas** [comment]
:+1:

**Comment by tpolecat** [comment]
:+1:

**Comment by adelbertc** [comment]
:+1:

**Comment by stew** [comment]
:+1:

**Comment by larsrh** [comment]
Pretty sure this is approved :smile:

**Comment by larsrh** [comment]
Now on the website: typelevel/typelevel.github.com#97.
