### ISSUE TITLE
Doc hosting

### ISSUE THREAD

**Issue by larsrh** [typelevel/general#18]
[docs.typelevel.org](docs.typelevel.org) hosts some Scaladocs of current or ex-member projects. However:
* they're outdated; because
* docs are also served by Sonatype directly (via [javadoc-badge](https://github.com/xuwei-k/javadoc-badge)).

Removing the domain altogether would probably be beneficial. Potential risk: Breaking links.

**Comment by larsrh** [comment]
Given that there's no opposition to this, I will discontinue the domain altogether by next week.

**Comment by milessabin** [comment]
:+1:

**Comment by fommil** [comment]
It need to update our ensime CI jobs

**Comment by larsrh** [comment]
Sorry, wasn't aware you were using that hostname.

**Comment by fommil** [comment]
Easy fix :-)
