### ISSUE TITLE
Typelevel membership for banana-rdf

### ISSUE THREAD

**Issue by milessabin** [typelevel/general#2]
+ banana-rdf is a library for RDF, SPARQL and Linked Data technologies in Scala.
+ banana-rdf supports the [Code of Ethics and Professional Conduct](http://www.w3.org/Consortium/cepc/).

See https://github.com/banana-rdf/banana-rdf

**Comment by milessabin** [comment]
Tagging @stacycurl.

**Comment by milessabin** [comment]
:+1:

**Comment by InTheNow** [comment]
@milessabin Thanks! There's also a gitter in case anyone has any questions - https://gitter.im/banana-rdf/banana-rdf

**Comment by travisbrown** [comment]
:+1:

**Comment by InTheNow** [comment]
Any updates on the membership, please?

**Comment by milessabin** [comment]
banana-rdf meets the criteria for incubator membership outlined in https://github.com/typelevel/general/issues/5, however those criteria are themselves provisional, so it's still somewhat hanging in the air.

My apologies for leaving you hanging this way ... it's my fault for not having the process more fully in place before encouraging people to apply.

**Comment by InTheNow** [comment]
@milessabin No apology needed, really :) 

One of the reasons I was keen to apply so early was to help "kickstart" the process - version 0.0.1 is always going to be unpolished

**Comment by larsrh** [comment]
Consensus appears to be that `banana-rdf` qualifies for incubator membership. Once the new website is live, I'm going to write down the steps required to add the project to the site, and then we can close this.

**Comment by larsrh** [comment]
Sorry for the delay. PR to add it to the website is pending: typelevel/typelevel.github.com#91.
