### ISSUE TITLE
Create legal entity for Typelevel

### ISSUE THREAD

**Issue by milessabin** [typelevel/general#20]
During the organization of the two Typelevel Summits just past it became very clear to the organizers (especially me, approaching potential sponsors, collecting donations, paying out bursaries, handling ticket sales, booking venues, etc., etc.) that a legal entity, preferably with a bank account that can be used to make and receive international payments, was essential. In practice all of this was handled through my company, Underscore Consulting, which was fine as a short term one off (well, twice off) arrangement, but isn't really suitable going forward.

I asked my accountant about this, and her advice is to set up a [company limited by guarantee](http://www.companylawclub.co.uk/companies-limited-by-guarantee). The salient points are,
+ Such a company has no share capital ... it's organized around a common purpose rather than being profit seeking.
+ It has members rather than shareholders, and they can be located anywhere in the world.
+ Individual members are protected from the liabilities taken on by the company (eg. nobody will be personally liable if an event should fail for some reason).

Other than that, such a company is just like any other UK registered company: it can have a bank account, be registered for sales tax, take payments, issue invoices, etc. etc.

I've discussed this with @non and @larsrh and the three of us are happy to get this set up with us as the three initial members if there's consensus that this is the right thing to do. If that's done, I would go on to set us up with a bank account.

**Comment by larsrh** [comment]
I think it's a good idea. I'd suggest a discussion period of, say, two weeks, so that we can get started soon.

**Comment by non** [comment]
Now that we're doing summits and events I agree that this makes sense. I also agree with @larsrh that we should leave this open for a discussion period, in case folks have questions or concerns.

**Comment by fommil** [comment]
:+1:

**Comment by AlecZorab** [comment]
I've had several discussions with Miles that have ended with me saying "this would be easier if you had a proper legal entity". I am a very definite :+1: on this. 

I'd also recommend that, as part of the process, a policy be put together as regards corporate donations, sponsorship etc.

**Comment by milessabin** [comment]
@AlecZorab do you have anything in mind that could be a model for a policy for corporate donations, sponsorship etc.?

**Comment by AlecZorab** [comment]
I do not. It's probably orthogonal to this conversation anyway.

**Comment by adelbertc** [comment]
:+1:

**Comment by milessabin** [comment]
There don't seem to be any objections to this proposal, so I'll make a start on this this week unless someone posts in the next day or two.

**Comment by milessabin** [comment]
Putting the wheels in motion now ...

**Comment by milessabin** [comment]
Fixed: https://beta.companieshouse.gov.uk/company/10224158

**Comment by adelbertc** [comment]
@larsrh Does this mean we can get Typelevel mugs now? :D

**Comment by larsrh** [comment]
Yes, I'm on it :smile:
