### ISSUE TITLE
Typelevel event organizers

### ISSUE THREAD

**Issue by milessabin** [typelevel/general#21]
Following the success of the first two Typelevel Summits we have had a few invitations to hold more Typelevel days as satellites of other conferences. This is really good news and I think we should try and meet as much of that demand as we can.

So far we have held the following kinds of event in roughly decreasing order of how much time, effort and cost is involved,
+ Conference with peer-reviewed presentations and on the day organization, refreshments, swag.
+ Unconference with on the day organization, refreshments, swag.
+ Hack day with minimal organization, snacks, no swag.

Organizer time is probably our scarcest resource, and it would be great if we could get together a list of people, with locations, who would be willing to help out with the organization of future events.

Please comment on this ticket if you would like to be involved.

**Comment by noelmarkham** [comment]
Happy to help with any of the above three for an event in London. Obviously around Scala Exchange in December is one of the obvious times to do something like this.

**Comment by kings13y** [comment]
+1. What Noel said :-)

**Comment by melrief** [comment]
I can help with a Zurich event

**Comment by lunaryorn** [comment]
Me and my coworker @muuki88 could help with events in the Munich area.

**Comment by kailuowang** [comment]
I can help with events in New York city.

**Comment by caente** [comment]
I can help as well in NYC

**Comment by rabbitonweb** [comment]
Hi, 

I don't know if Poland would be your target *BUT* before you scroll down let me quickly introduce the advantage:

* Poland has one of the strongest Scala community in Poland
* You can organize a summit in very original & extraordinary venues: e.g last year I've organized a unconference in castle like this one: http://www.visitopolskie.pl/store/resources/images/objects/640x300/b91b66db76d7f8e58cdcf50aba61f364.jpg 
* Let's be honest, Poland is cheap - in a way that for Londoner buying a beer in Poland is almost like having it for free :)
* Poland is nice and welcoming - has that typelevel attitude 

I've been organising meetups & conferences before - would be more then happy to help (or even lead if needed) doing Typelevel here in Poland.

**Comment by ShaneDelmore** [comment]
I'll follow up next week but may be able to help out in Portland, OR.

**Comment by gabro** [comment]
I organize the Milano SUG and the Scala Italy conference (that just took place in Venice) and I'd be happy to help organizing an event in Italy!

**Comment by gabro** [comment]
I organize the Milano SUG and the Scala Italy conference (that just took place in Venice) and I'd be happy to help organizing an event in Italy!

Our community is small but growing and an international event would be really beneficial to it! :)

**Comment by tpolecat** [comment]
Assuming we can get our act together and do PNWScala again (Portland, OR) I can help with an adjacent Typelevel event.

**Comment by fthomas** [comment]
I can help with events in Munich and Augsburg.

Should we move this list of people and locations to the wiki?

**Comment by tpolecat** [comment]
Not a huge deal but I would prefer a document in the repo so changes would go through a normal PR process and stay on people's radars. I have never had a positive experience with a wiki.

**Comment by ShaneDelmore** [comment]
Thomas gave me the thumbs up to take over PNW Scala.  It's officially on, and I am definitely up for integrating a Typelevel summit with it.

**Comment by larsrh** [comment]
Thanks to all of you for offering to be volunteers! As of #23 there's now [a file for this](https://github.com/typelevel/general/blob/master/event_organizers.md); anyone else who's interested please file a PR.

**Comment by rajmahendra** [comment]
@milessabin is there any pics share about past events ?

**Comment by milessabin** [comment]
@rajmahendra that's a question for the typelevel/general gitter channel :-)
