### ISSUE TITLE
Typelevel membership for Mouse

### ISSUE THREAD

**Issue by benhutchison** [typelevel/general#22]
Mouse is a small companion library to cats providing enrichments to std lib classes to ease functional programming and/or ease source compatibility with scalaz

Mouse supports the Typelevel code of conduct.

https://github.com/benhutchison/mouse

**Comment by milessabin** [comment]
:+1:

**Comment by larsrh** [comment]
Initial reactions seem to be in favour; let's give it another week :smile:

**Comment by larsrh** [comment]
Let's go ahead with this :tada:

**Comment by larsrh** [comment]
Membership now officially on the website. Thanks for waiting!

**Comment by benhutchison** [comment]
Thank you! ☺
