### ISSUE TITLE
Typelevel hack days at Hack the Tower, London

### ISSUE THREAD

**Issue by milessabin** [typelevel/general#27]
This issue is for tracking activity around the Typelevel hack days at Hack the Tower in London.

**Comment by milessabin** [comment]
The next event is on June 11th: http://www.meetup.com/london-scala/events/231404561/

**Comment by milessabin** [comment]
The July and August meetups will be hosted by Hydrogen at their Eastcheap offices while building work is done on the Salesforce tower: http://www.hydrogengroup.com/en/london.

**Comment by larsrh** [comment]
Have we got a date there yet?

**Comment by milessabin** [comment]
Tentatively 16th July and 13th August.

**Comment by larsrh** [comment]
Events are happening regularly now (see [events page](http://typelevel.org/events/)). There's also a dedicated [Gitter channel](https://gitter.im/typelevel/hack-the-tower).
