### ISSUE TITLE
Periodically export discussions from Gitter

### ISSUE THREAD

**Issue by larsrh** [typelevel/general#34]
[Some suggested on Gitter](https://gitter.im/typelevel/general?at=57542c4b9be9c5b637f0945b) that we should periodically export/archive discussions, because Gitter's own archive only goes back one year. [Gitter has an API](https://developer.gitter.im/docs/rest-api), so we could implement this ourselves.

**Comment by fommil** [comment]
a bot for gitter would also be great, responding to keywords and new users with boilerplate.

**Comment by ceedubs** [comment]
I also like this because I don't like the idea of all of this useful data disappearing if Gitter shuts down.

**Comment by larsrh** [comment]
It has been pointed out by @rossabaker that such a thing exists: [archive-gitter](https://github.com/minrk/archive-gitter). I will try and set up a prototype running on my personal server.

**Comment by larsrh** [comment]
Example: http://archive.typelevel.org/gitter/typelevel/general.json (raw Gitter output)

**Comment by larsrh** [comment]
I've set up a cronjob on my server which runs the archive script every hour and pushes it to the [archive](https://github.com/typelevel/archive) repository. If anybody wants to sit down and do it properly (deploying on Heroku or with Docker or some such), please go ahead. But I think it's good enough for now.
