### ISSUE TITLE
Typelevel mission statement

### ISSUE THREAD

**Issue by milessabin** [typelevel/general#36]
I have been using the following bullet points as a summary of the Typelevel mission in the talks I've given on Typelevel recently,

> Typelevel is a community of projects and individuals organized around ...
> - Pure, typeful, functional programming in Scala
> - Independent, free/libre and open source software
> - A desire to share ideas and code
> - Accessible and idiomatic learning resources
> - An inclusive, welcoming and safe environment

I've also been pointing people at [Erik's talk at Scala World in 2015](https://www.youtube.com/watch?v=iKyIKozv8a8) for elaboration on the community aspect.

I believe that both the bullets and Erik's talk are consistent with what we've discussed and our tacit understanding, but it would be good to have this endorsed (or not) a little more formally.

**Comment by milessabin** [comment]
Just watching Erik's talk again now, he has a very nice single sentence summary which I think works very well,
> Remove barriers to doing functional programming in Scala

**Comment by kailuowang** [comment]
that's the sentence came to my head when you mentioned his talk .

**Comment by ceedubs** [comment]
I think Erik's statement is a nice one-liner and Miles's bullet points are a nice elaboration. 👍 all around.

**Comment by stew** [comment]
:+1:

**Comment by rossabaker** [comment]
Now covered by [the charter](https://github.com/typelevel/governance/blob/main/CHARTER.md.
