### ISSUE TITLE
Clarify the list of people who can tweet from the @typelevel account

### ISSUE THREAD

**Issue by milessabin** [typelevel/general#37]
Currently this is,
- @milessabin
- @larsrh 
- @non (aka `@d6` on Twitter)
- @tixxit

**Comment by rajmahendra** [comment]
Account is not active more than a month :(

**Comment by milessabin** [comment]
Are you looking in the right place? See [here](https://twitter.com/typelevel/status/827587947327344640) for instance.

**Comment by rajmahendra** [comment]
oops, my bad sorry. Just now I saw the Pinned symbol on top :)
