### ISSUE TITLE
Typelevel membership for Scala Exercises.

### ISSUE THREAD

**Issue by raulraja** [typelevel/general#38]
- Scala Exercises it's a platform and framework for Scala devs to learn about Scala libs.
- It follows the Typelevel Code of Conduct.
- it follows a typeful, purely functional approach where possible.
- It features many Typelevel libs exercises and more to come.
- It backlinks to Typelevel as reference for learning FP in Scala.
Thanks for your consideration :)

https://www.scala-exercises.org/
https://github.com/scala-exercises/scala-exercises

**Comment by tpolecat** [comment]
I think this would be a great addition. 👍

**Comment by milessabin** [comment]
Also :+1:

**Comment by larsrh** [comment]
Membership now officially on the website. Thanks for waiting!
