### ISSUE TITLE
Typelevel membership for Fetch

### ISSUE THREAD

**Issue by raulraja** [typelevel/general#39]
- Fetch is a library built on top of Cats that provides efficient data access from heterogeneous datasources.
- it follows a typeful, purely functional approach.
- it follows the Typelevel Code of Conduct

https://github.com/47deg/fetch/blob/master/CONTRIBUTING.md
https://github.com/47deg/fetch
http://47deg.github.io/fetch/docs

**Comment by milessabin** [comment]
I'd love to see this project join Typelevel ... :+1:

**Comment by larsrh** [comment]
Membership now officially on the website. Thanks for waiting!
