### ISSUE TITLE
Consider setting up a discourse server

### ISSUE THREAD

**Issue by larsrh** [typelevel/general#41]
There are plans to consider this in Ensime (ensime/ensime.github.io#171), but this actually makes sense as a central Typelevel "service" too.

_Clarification:_ This is a ticket for discussion. It's not a done deal.

**Comment by milessabin** [comment]
I'm really not in favour of a move. For better or worse we've established communities around gitter and I don't think we should lose unless there's something very concrete and very significant to be gained from moving.

**Comment by larsrh** [comment]
As far as I can tell one of the advantages is that it offers a long-term solution for storing discussions; in fact, this feature is even built in. There's no such thing for Gitter. And in my personal experience, searching Discourse is easier than searching Gitter.

**Comment by BennyHill** [comment]
The other day i wanted to find some old posts on docker from this channel:

`docker site:https://gitter.im/typelevel/general/archives` 

Seems OK to me

**Comment by rossabaker** [comment]
I don't know when typelevel/general started, but I found the initial message from another chat in January 2015.  I think the archives are fine until Gitter dies or turns heel.  To protect our history without upsetting the established community, maybe something like a backup with [archive-gitter](https://github.com/minrk/archive-gitter), or some other API solution?

**Comment by larsrh** [comment]
I didn't know that existed, but it seems like a reasonable solution for permanent archival.

**Comment by fommil** [comment]
I like that's it is libre, and not some proprietary vaporware like gitter. Still, it's not a replacement for gitter it's a different medium and would perhaps allow longer discussions around individual topics. Arguably that could also happen on tickets.

**Comment by larsrh** [comment]
This seems to be overwhelmingly not desired. Closing this for now.
