### ISSUE TITLE
Typelevel representative at the Scala Center Advisory Board

### ISSUE THREAD

**Issue by larsrh** [typelevel/general#42]
## What is the Scala Center Advisory Board

To quote @propensive,

> The Advisory Board is a separate body from the Scala Center, much as many governments have separate legislative and executive branches: the Advisory Board makes recommendations to the Scala Center on the work we should do, but it’s the Scala Center’s job to execute those recommendations.
>
> It currently has seven voting members: representatives from each of our six sponsors, plus Bill Venners, the community representative. Additionally the Executive Director of the Scala Center, Heather Miller, sits on the board to report on the Scala Center’s activities, and provide advice on the feasibility of the proposals under consideration, and Martin Odersky is the technical advisor to the board.

(from http://www.scala-lang.org/blog/2016/05/30/scala-center-advisory-board.html)

## Proposal

The Advisory Board has invited us to nominate a member of the Typelevel community to serve as a community representative, alongside Bill Venners. After some brief private discussions, @milessabin and I decided that whether or not we should accept this offer and who we pick should be decided in the open. Initial feedback from the Board supports this.

## Obligations

To quote @propensive again,

> The time commitment would be approximately two hours of meeting time per quarter, plus the commitment to being visible as a representative of the community (which would be shared with Bill). Meetings would be mostly done over Google Hangouts (though we aim for one physical meeting a year, colocated with a conference), and the next meeting is planned for some time in second half of November.

## Questions

1. Should we accept this offer?
2. If yes, who should we pick?

## Provisions

@milessabin and me think that it would be a good idea for the Typelevel representative to rotate every once in a while. @odersky has confirmed that this would be acceptable under two conditions:

1. The tenure should be at least one year to avoid having someone else at every other meeting.
2. The Advisory Board needs to confirm each successor.

Note that both points also apply to the initial candidate.

## Nominees

Feel free to nominate people in this thread, except for
- @non
- @milessabin 

who have privately expressed their preference not to be nominated (which is _not_ a judgement on the proposal itself).

**Comment by BennyHill** [comment]
> 1. Should we accept this offer?
2. If yes, who should we pick?

Yes, @larsrh

**Comment by ShaneDelmore** [comment]
1. Yes
2. @tpolecat

**Comment by propensive** [comment]
To be a bit more open about how the nomination came about, the advisory board voted at the last meeting to invite @non to take a seat on the board, and if he declined, to offer the seat to Typelevel to nominate someone else. @non was not satisfied that he would have enough time to devote to the process, and so we invited Typelevel to nominate someone.

The minutes from the last meeting don't fully reflect this detail, as we wanted to ask Erik before making any announcement.

Although the advisory board has no jurisdiction over how Typelevel chooses its representative, I would make the suggestion that nominations from existing members of the advisory board carry no material weight in the process.

**Comment by non** [comment]
I propose that we nominate candidates in this thread, and then if we have more than one interested party who is nominated, to decide how to vote on the candidate.

For my part, I think @larsrh and @tpolecat are both people I trust to be involved with the board (if they were interested). Similarly, I think @mpilquist could also be an excellent choice.

**Comment by milessabin** [comment]
I agree with @non ... I'd also add @travisbrown to the list.

**Comment by milessabin** [comment]
Oh, and that implies that my answer to question 1 is "yes".

**Comment by cvogt** [comment]
nominating @lihaoyi

**Comment by cvogt** [comment]
+1 to Lars! (got the topic wrong before)

**Comment by adelbertc** [comment]
+1 to @tpolecat . I trust him very much, he's actively on both IRC and Gitter always being super helpful, and can bring a strong FP presence to the board.

**Comment by raulraja** [comment]
+1 @tpolecat +1 @larsrh for the very reasons others have mentioned. Being part of the scala center board myself I think both of them would be a great representation of the growing FP Scala community.

**Comment by tpolecat** [comment]
Yes, I think we should do this, and I also wish to nominate @travisbrown. His knowledge, background, reputation, and temperament would make him a great representative.

Re: me: I appreciate the nominations, but I don't think I am the best person for this role (and in any case I don't have the bandwidth to take on another responsibility right now). So I don't wish to be considered, at least this time around.

**Comment by adelbertc** [comment]
Given @tpolecat 's comments I change my vote for @larsrh for similar reasons as above

**Comment by dwhitney** [comment]
@larsrh or @travisbrown both sound like great choices. Might be easier to have someone living in Europe

**Comment by rossabaker** [comment]
Instead of counting votes on a GitHub issue while nominees are still coming and going, I'd recommend we use this thread for nominations and process, and then use one of the free online voting sites to choose among the accepting nominees according to process.

**Comment by coltfred** [comment]
@milessabin has been very visible, especially with his recent enhancements to scalac and promoting the TL fork of scalac. I think he'd be my `#1` choice. 

@tpolecat would just have a bucket over his head anyways! :laughing:

**Comment by propensive** [comment]
@dwhitney I don't think there's any particular benefit in being in Europe or the US. The majority of attendees to the meetings are US-based, and we'll try to hold meetings at a time that's acceptable to everyone. IIRC, the last one was at 9am PST, 5pm CET.

**Comment by larsrh** [comment]
Thanks for the nomination. I'd be happy to take it.

Personally I'd nominate @travisbrown.

**Comment by travisbrown** [comment]
I'd be happy to do this if we needed someone (and I appreciate the nominations), but I think @larsrh is the best person for the job, and I'd prefer not to accept the nomination now that we know he's in the running. 😄

**Comment by larsrh** [comment]
@mpilquist Would you accept a nomination? If yes, that'd make the two of us, if I'm reading this thread correctly.

To be clear: I don't mind competition at all; in fact, I'd like to encourage it. I'd be slightly uneasy with being the single contender and thus "by default" ending up as the nominee. No hard feelings from my side if the vote goes towards someone else. So @travisbrown, if you change your mind, please tell.

**Comment by tpolecat** [comment]
(There might also be nominations from other timezones; this has only been open 7h.)

**Comment by larsrh** [comment]
Right, that's true. @propensive asked us for a quick answer whether we'd want to do this in the first place, and I think the answer is pretty much "yes". So I think we can take a couple of days to let more comments flow in.

**Comment by propensive** [comment]
Yes, that's fine. The reason for asking for a quick answer was mainly to avoid it dragging on for weeks, and so that we can plan a date/time for the next meeting that works for everyone.

**Comment by BennyHill** [comment]
@larsrh @tpolecat  @travisbrown @mpilquist

You make elections so polite, it's a shame that you can't all win. Thankyou :smile:

**Comment by milessabin** [comment]
> To be clear: I don't mind competition at all; in fact, I'd like to encourage it. I'd be slightly uneasy with
> being the single contender and thus "by default" ending up as the nominee

Understood, but if this thread converges on there being a universally acceptable candidate, approved of by the other nominees as well, then I think that's absolutely fine, in fact probably the best outcome. Our default decision making mechanism is "by consensus" and that would be completely in keeping.

**Comment by larsrh** [comment]
Fair enough.

**Comment by mpilquist** [comment]
@larsrh Like Travis, I'd be happy to perform this role and I'm flattered by the nomination, but I'm happy for you to take this position and I don't see the need to have a vote. :)

**Comment by dwijnand** [comment]
I agree to the nominated candidates, but I would also like to nominate @fommil.

**Comment by fommil** [comment]
@dwijnand shucks, but I already had my priorities discussed at the last meeting and I think others here would be far superior diplomats :-)

**Comment by AlecZorab** [comment]
Since we seem to be adopting a scattergun approach to to nominations, I'd like to :+1: for @travisbrown @larsrh @fommil. I'd also suggest that we should have a formal vote to choose among the interested nominated parties, so long as the number of them is > 1.

It doesn't look like many other people are likely to get nominated, so is it maybe worth moving to a vote starting either today or tomorrow?

**Comment by milessabin** [comment]
@AlecZorab as far as the mechanism goes, please see #43.

**Comment by larsrh** [comment]
Thanks again for the endorsements.

@AlecZorab As far as I read it, @travisbrown didn't accept the nomination. I'm not sure about @fommil – could he please clarify?

If he also withdraws, I think that leaves me. Let's say we keep this open until Wed, 12th October, 12:00 noon UTC.

**Comment by easel** [comment]
I'm also in favor of accepting the offer, and @larsrh being the representative. If @travisbrown decides to change his mind on the nomination, he would also be a great choice.

**Comment by fommil** [comment]
I don't have time, sorry Lars. You're it :-P

**Comment by larsrh** [comment]
Since the discussion period I suggested on Monday has now ended, I think we can close this. I'll write a public blog post on the weekend explaining the situation and my acceptance.

Thank you all for your trust!
