### ISSUE TITLE
Typelevel membership for scoverage

### ISSUE THREAD

**Issue by sksamuel** [typelevel/general#44]
- Scoverage is a code coverage tool for scala projects
- We want to move into a pure functional approach (as far as is possible when writing a compiler plugin)
- Scoverage seeks to aid pure functional programming
- It has a typelevel derived [code of conduct](https://github.com/scoverage/scalac-scoverage-plugin/blob/master/conduct.md)
- We have a [quorum in favour](https://github.com/scoverage/scalac-scoverage-plugin/issues/185)

**Comment by larsrh** [comment]
As far as I understand, scoverage is also used in some Typelevel projects, for example cats. I think it makes sense to join, since scoverage is a tool which helps increasing code correctness – one of the aims of Typelevel in general.

**Comment by BennyHill** [comment]
@larsrh That is correct. 

More recent WIP is [coverage of the scala compiler itself](https://codecov.io/gh/BennyHill/scala/tree/675da3382af310bfd808d2b3e2477bba344bd70f) and hence potentially TLS as well/instead.

**Comment by larsrh** [comment]
@sksamuel Incubation status is approved. Welcome! Please file a pull request to https://github.com/typelevel/typelevel.github.com, adding the project to `_data/incubator.yml`.

**Comment by sksamuel** [comment]
https://github.com/typelevel/typelevel.github.com/pull/131
