### ISSUE TITLE
Typelevel membership for ScalaFX 

### ISSUE THREAD

**Issue by rajmahendra** [typelevel/general#46]
_simplifies creation of Java FX - based user interfaces in Scala._

**ScalaFX** is a UI DSL written within the Scala Language that sits on top of Java FX 2 and Java FX 8. Every ScalaFX application is also a valid Scala application. It supports full interoperability with Java and can run anywhere the Java Virtual Machine (JVM) and Java FX 2 or Java FX 8 are supported.

[Organization](https://github.com/scalafx) | [Core Repo](https://github.com/scalafx/scalafx) | [Website](http://www.scalafx.org) | [Documentation](http://www.scalafx.org/docs/home) | [Issue Tracker](https://github.com/scalafx/scalafx/issues) | Team: [Core](https://github.com/orgs/scalafx/people) , [Committers](https://github.com/scalafx/scalafx/graphs/contributors) | News: [Release News](http://www.scalafx.org/news/releases) , [General](http://www.scalafx.org/news) | Forum: [Dev](https://groups.google.com/forum/#!forum/scalafx-dev) , [User](https://groups.google.com/forum/#!forum/scalafx-users) | [Gitter](https://gitter.im/scalafx/scalafx) |

**RelatedProjects:** [scalafx.g8](https://github.com/scalafx/scalafx.g8), [scalafx-ensemble](https://github.com/scalafx/scalafx-ensemble), [ScalaFXML](https://github.com/vigoo/scalafxml)

**TypeLevel core goal complaint**
- Open Source : Yes
- Functional: Open for improvement
- Shared: Yes
- Resources: Yes
- Friendly: Yes
- Modular: Open for improvement 

CC/@jpsacha

**Comment by larsrh** [comment]
@rajmahendra Thank you for your proposal. Could you please clarify the following points from the membership criteria:

> (1) There must be a consensus amongst the project's stakeholders that they want to join Typelevel.
> 
> (2) The project must be willing to support the Typelevel code of conduct or something equivalent.

**Comment by rajmahendra** [comment]
@larsrh 
@jpsacha , @Alain-Bearez and @rajmahendra like to join. 
As I mentioned above, I hope the project is already following most of the Typelevel code and open for any improvements.

**Comment by larsrh** [comment]
@rajmahendra Great. What about the CoC?

**Comment by milessabin** [comment]
@rajmahendra we usually like to see a code of conduct fairly prominently advertised on the projects website and repos. See the cats [site](http://typelevel.org/cats/contributing.html) (towards the bottom) and [repo](https://github.com/typelevel/cats#community) for an example.

**Comment by rajmahendra** [comment]
@larsrh @milessabin  Added in repo https://github.com/scalafx/scalafx . Site will be updated soon

**Comment by jpsacha** [comment]
Just learned that, Typelevel [endorsed](http://typelevel.org/blog/2016/12/17/scala-coc.html) the new [Scala Code of Conduct](https://contributors.scala-lang.org/t/please-read-scala-code-of-conduct/28), giving an option to use either one for Typelevel projects. I think we should go with [Scala Code of Conduct](https://contributors.scala-lang.org/t/please-read-scala-code-of-conduct/28) as covering broader (?) community. 
What do you think?

**Comment by larsrh** [comment]
After leaving this open for a while, nobody from the current Typelevel project members has given this ticket a :+1:. Hence I'll close this for the time being. Feel free to reopen once a couple of people acknowledge the membership request.

**Comment by rajmahendra** [comment]
@larsrh I was waiting for someone to answer @jpsacha . i have already sent a pull request as mentioned above.

**Comment by rajmahendra** [comment]
@larsrh ScalaFX is now adopting the CoC http://www.scalafx.org

**Comment by rajmahendra** [comment]
To: @milessabin , @non , @stew , @ceedubs , @adelbertc , @BennyHill , @folone , @fthomas , @kailuowang, @propensive , @rossabaker , @tixxit , @tpolecat @larsrh 
Sorry for flooding this comment with lots of mentions, Unfortunately, this issues have not received much attention from the community nor from the core team only @milessabin & @larsrh posted their views so far, 
This issue is created 120 days ago.  As I mentioned in the ticket this project is supporting the core principal of Typelevel 

**TypeLevel core goal complaint**

Open Source: Yes
Functional: Open for improvement
Shared: Yes
Resources: Yes
Friendly: Yes
Modular: Open for improvement

and also added CoC to their website. ( as per @milessabin &@larsrh comments)

I have also posted two open invites to all the members in the Gitter channel room, this issue has not received any:+1: or comments.   

In my knowledge, I hope this project is well matured for Incubator membership. Let me know your views? If close/no comments from community means rejected,  then no need to move further :)

**Comment by milessabin** [comment]
I think for me the concerns centre on Java FX ... as I understand it, Java FX is an inherently imperative framework, and even if a Scala DSL improves it's ergonomics, it's not clear for me that this is enough to bring it into our ambit. Have I got this wrong?
