### ISSUE TITLE
Cats-scalatest addition to typelevel

### ISSUE THREAD

**Issue by coltfred** [typelevel/general#47]
I'm the author of [cats-scalatest](https://github.com/IronCoreLabs/cats-scalatest). It seems silly that I haven't added it as a typelevel project so that people can find it when they start using cats.

I'm committed to the CoC and have been active in the typelevel community.

Is there anything else I need to do to get it added?

**Comment by larsrh** [comment]
Advertise this ticket and wait for the :+1: to roll in :rocket:

**Comment by non** [comment]
👍

**Comment by coltfred** [comment]
Thank you all very much. I'll add the CoC to the README today. Should I open a separate ticket for changes to the typelevel.org site or can this serve as that ticket?

**Comment by coltfred** [comment]
I've added the CoC.

**Comment by larsrh** [comment]
@coltfred Welcome! Please add yourself to [the incubator](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml) by sending a PR.
