### ISSUE TITLE
Incubator Status for TwoTails

### ISSUE THREAD

**Issue by wheaties** [typelevel/general#48]
[TwoTails](https://github.com/wheaties/TwoTails) is a compiler plugin to add support for mutual tail recursion within the same object/function scope. The goal of this project is twofold: 

1. Get people to use it, discover any more bugs and fix those bugs before...
2. Opening a PR to Scala itself

Addressing the 4 point criteria:

1. I'm the only person working on this. So I verify there is consensus between me, myself and I.
2. I support your CoC.
3. I swear this does not add side-effects! It's all about recursion. If that ain't functional, I've been learning the wrong things.
4. I have docs in the README and, quite honestly, I probably need to add a few more examples.

**Comment by larsrh** [comment]
@wheaties Welcome! Please add yourself to [the incubator](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml) by sending a PR.

Please also make sure to link to the CoC from your README.
