### ISSUE TITLE
Clarify membership criteria and process for projects joining Typelevel

### ISSUE THREAD

**Issue by milessabin** [typelevel/general#5]
I propose the following criteria and process for a project to join Typelevel,
1. There must be a consensus amongst the project's stakeholders that they want to join Typelevel.
2. The project must be willing to support the Typelevel code of conduct or something equivalent.
3. The project should be aiming to promote pure, typeful, idiomatic functional programming in Scala.
4. If the primary output of the project is software artefacts then it should aim to complement them with accessible, idiomatic documentation.

Things which are not requirements are,
- The project does not need to be nominated by an existing Typelevel member.
- At the time of joining, the project does not have to fully exemplify pure, typeful, idiomatic functional programming. There is, however an expectation that it will aim to move in that direction during an incubation period. Typelevel members are expected to encourage and help with that development.

The process for joining is as follows,
1. An issue must be created in this issue tracker proposing Typelevel membership for the project.
2. Criteria (1) and (2) should be verified.
3. Suitability of the project for joining Typelevel, and the suitability of Typelevel membership for the project, should be discussed constructively.
4. If there are no unaddressed objections to the projects joining Typelevel after a period of one week, then it will move into the incubator stage.
5. TBD: criteria for moving from incubation to full membership.

Note that the term "incubator" is chosen carefully ... incubators protect developing newborns from a challenging world, not vice versa.

**Comment by denisrosset** [comment]
Regarding "pure": depending on the domain, how far should things go?

Concrete example: I'm writing a linear algebra library for Scala/Spire, focused on exact arithmetic. I haven't found a way (barring full dependent types) to make it fully pure/typesafe without completely changing the way mathematicians write linear algebra code.

**Comment by denisrosset** [comment]
Also add requirement 5. the project has an explicit statement regarding binary compatibility.

**Comment by adelbertc** [comment]
One thing we may want to add is something about maintaining - perhaps something like there should be at least 1 "active maintainer", perhaps listed in README, who people can expect to reply to issues/address PRs, etc.

**Comment by tpolecat** [comment]
There was a question on the gitter channel about the use of "idiomatic", which I believe is intended to capture the idea that this we're interested in **Scala** programming (as opposed to, for example, doing Java or Haskell programming in Scala).

Perhaps this language could be clarified or maybe just set aside … the phrase *functional programming in Scala* might be sufficient on its own.

**Comment by adelbertc** [comment]
In my mind, the bit about:

> At the time of joining, the project does not have to fully exemplify pure, typeful, idiomatic functional programming. There is, however an expectation that it will aim to move in that direction during an incubation period. Typelevel members are expected to encourage and help with that development.

is important. In the previous life of Typelevel I could pretty much depend on any "Typelevel" project and expect seamless or easy integration of other libraries into RT FP code, e.g. shapeless + scalaz, spire + scalaz.

That being said I see merit in not having a strict requirement that everything be bound to say, `scalaz.Task` or the currently non-existent cats `IO`/`Task`, but it shouldn't be designed in such a way that if one were writing RT code the effort it would take to bring the library in without disrupting the functional nature would be high. Now the tricky part is defining what constitutes "too much effort" - it could perhaps be defined as "clear separation between the effectful and pure code."

**Comment by milessabin** [comment]
@adelbertc please bear in mind that the process I've sketched above only gives criteria for joining the Typelevel _incubator_ ... point (5), transition to full membership is still TBD.

Several comments in this thread have proposed stricter and/or more detailed criteria ... would the proposers be happy for those to be listed under point (5), ie. as parts of the criteria for moving from incubator status to _full_ Typelevel membership status?

I'm very keen that we have quite lax criteria for the first rung of the ladder, and that we place a strong emphasis on the collective responsibility of Typelevel members for helping new incubatees move to full membership status. If anything, the second sentence in that clause ("Typelevel members are expected to encourage and help with that development.") is the most important.

We _will_ need to make a clear distinction between the kinds of endorsements Typelevel makes for incubator vs. full member projects, but I think that that is somewhat orthogonal to the process itself.

**Comment by adelbertc** [comment]
@milessabin Ah right, my mistake, good point.

In that case, I am OK with moving the stricter requirements to "full membership." I definitely agree on keeping the criteria more lax for incubator status, and more thorough evaluation/help from TL folks to move from incubator to full.

**Comment by adelbertc** [comment]
So, what are the next steps on this?

**Comment by milessabin** [comment]
Would someone like to summarize the full set of stricter requirements for full membership?

**Comment by adelbertc** [comment]
Proposal for strict membership requirements:

* The project should exemplify pure, typeful, idiomatic functional programming. It should not be deeply rooted in things such as side-effects and mutation - put differently, it should be fairly easy for those working in pure functional code bases to bring in your library. That being said, mutation and other side-effecting properties is not strictly disallowed, but should have a good documented reason for doing so (e.g. performance, limitation of the language)
* Documentation for the code should (a) exist (b) be machine checked so as to enforce all documentation is up to date. [Tut](https://github.com/tpolecat/tut) is useful for this.
* At least one active maintainer of the project who will field pull requests, issues, questions, etc.
* Some versioning scheme that communicate binary and/or source compatibility

**Comment by milessabin** [comment]
Thanks for that. I'll pull this all together as a wiki page.

**Comment by milessabin** [comment]
I've pulled this out as a document in this repo [here](https://github.com/typelevel/general/blob/master/governance/membership.md) rather than as a wiki page so that it's easier to create issues and PR around it.

**Comment by InTheNow** [comment]
>  it should be fairly easy for those working in pure functional code bases to bring in your library.

This sounds fine, but perhaps also implies that the new library (where possible/feasible) also works on the same platforms of the other typelevel projects and is compatible with the dependencies of the the existing libraries.

A draconian definition would be that new libraries cross-compile and re-use typelevel libraries wherever possible.

This will for sure hit some existing libraries, but fortunately we are not draconian.

**Comment by fommil** [comment]
given that we have to interact with the scala internals, we may struggle to ever be "pure" in ENSIME :stuck_out_tongue:

**Comment by milessabin** [comment]
@fommil that's understood,

> ... mutation and other side-effecting properties is not strictly disallowed, but should have a good documented reason for doing so ...

**Comment by davegurnell** [comment]
Something @adelbertc said earlier rang true with me...

One of the potential downsides of welcoming lots of libraries is that Typelevel could end up with lots of unmaintained libraries on the roster.

It may be worth having an "emeritus" or "inactive" status for libraries that were part of Typelevel but have stopped being actively maintained.

Then again, perhaps this is a proposal for premature optimisation. This problem can be solved later if it occurs (it's a good problem to have, after all).

**Comment by milessabin** [comment]
Agreed. We have the beginnings of rules for joining, but it's not so clear how projects leave. In the doc I pulled out from this issue I added the text,

> The criteria listed above should be actively maintained and if they cease to hold and that isn't rectified with a reasonable period then the project's membership might revert to incubator status or revoked.

But I think there's a lot more that could and should be said.

**Comment by denisrosset** [comment]
> The project should exemplify pure, typeful, idiomatic functional programming. It should not be deeply rooted in things such as side-effects and mutation - put differently, it should be fairly easy for those working in pure functional code bases to bring in your library. That being said, mutation and other side-effecting properties is not strictly disallowed, but should have a good documented reason for doing so (e.g. performance, limitation of the language)

I love this.

I'm writing a computational group theory library for Scala (denisrosset/alasc), and I have to draw a line concerning the properties that can be easily encoded using Scala types, and which cannot be. The type system expressibility is one problem, the combinatorial explosion of types is another.

For those interested, this is a known problem, with the following solution using dynamic types: http://www.gap-system.org/Doc/Talks/paper.ps

**Comment by InTheNow** [comment]
Ok, I know C++ is not Scala, and Boost is not Typelevel. That said, FYI:

http://www.boost.org/development/requirements.html

http://rrsd.com/blincubator.com/

**Comment by dwijnand** [comment]
Is there any reason this issue is still open?

As Miles mentioned above, the membership criteria and process are detailed now in https://github.com/typelevel/general/blob/master/governance/membership.md.

**Comment by rajmahendra** [comment]
my views...
* Need a group of people who can check new addition request and post a comment on how to bring the project on board, giving suggestions, ideas, etc. I mean some dedicated members of executive committee. 
* To validate project to full, there should be some point system or some filtering. 
* If there is some regular meeting (fixed time meetings it will be good to join and share ideas etc. 
* If we have some way of announcing like newsletter it will give info to all the members. like a newly added project, new open request, new release, articles etc. it will be easy for people who do not check will be intimated by mail. 
* keep a day for people to check and comment thumbs up/down on ideas

**Comment by rossabaker** [comment]
This is now covered in the [charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria).
