### ISSUE TITLE
[Typelevel Summit NYC, 2017] format discussion	

### ISSUE THREAD

**Issue by kailuowang** [typelevel/general#50]
This time the summit is planned to collocate with NEScala again. Shall we have a one day of talks and one day of unconference like last time? For talks do we want to continue do curated talks right? (NEScala is going to have community voting on talk proposals). 
@larsrh will be overseeing the CFP process. Anyone else wants get involved in the review process?

**Comment by adelbertc** [comment]
Last year the committee was done via nominations I think.

**Comment by tpolecat** [comment]
We had some discussion at SBTB and I *think* what we decided was:

- We will be before NEScala, at the same venue.
- We will close our CFP before NEScala opens theirs, to avoid conflicts.
- I can't remember if we settled on one day or two.

@milessabin was driving the bus so I think he can probably fill in some details.

**Comment by larsrh** [comment]
@tpolecat Sounds good.

I think the following order of days makes the most sense:

Day 1: Typelevel Summit (with select talks)
Day 2: NE Scala (with select talks)
Day 3: Joint unconference

This is of course under the assumption that the attendees of the Summit is a subset of the attendees of NE Scala.

**Comment by dwhitney** [comment]
my understanding is inline with @tpolecat and @larsrh. (I am leading the organizational effort of NE Scala this year)

**Comment by milessabin** [comment]
Yup, we more or less converged on the format that @larsrh mentioned. I think a shared unconference day makes sense.

**Comment by adelbertc** [comment]
👍 to the format.

I think the next question is how we want to curate talks - committee voting or community voting? If committee, do we want to reuse the same committee as last year?

**Comment by tpolecat** [comment]
I thought we ended up with a really good selection of talks last year, and I think it's not the set of talks we would have gotten through voting. So I'm happy with how it turned out. But I think the process wasn't that great. Seeing everyone else's votes made me self-conscious and in the end I think Miles and Lars ended up doing most of the work. I don't have an immediate suggestion for improving it though.

Also do we want to invite a special speaker this time?

**Comment by non** [comment]
I thought having a committee voting was reasonable; I share @tpolecat's feelings a little bit but in the absence of a better way to do committee voting I'd be fine with repeating the process.

**Comment by adelbertc** [comment]
Shall we keep the same committee as last year/how shall we select the committee this year?

**Comment by caente** [comment]
we should at least enumerate who those people are, even though I'm sure most of us know who they are without know who was on it last year

**Comment by tpolecat** [comment]
@adelbertc maybe ask for volunteers? It would be nice to get some new people involved. I'll do it if we're running short but I'd be happier letting someone else take a turn.

**Comment by adelbertc** [comment]
I am open to helping as well if we need folks.

**Comment by larsrh** [comment]
Update to the current situation: The fine folks organizing NE Scala are still looking out for a venue. I think it's best if we put out a CfP with a vague-ish date ("mid-March, colocated with NE Scala") ASAP. We can close it end-January to leave enough time for NE Scala to do their thing.

**Comment by larsrh** [comment]
They're currently looking at March 17–19. I think equipped with that we can start the CfP process. @sellout, I remember you having opinions about some web service to use for that? Google Docs was quite cumbersome in the past.

**Comment by sellout** [comment]
Yeah – http://papercall.io – MoonConf used it last year, and it was great, IMO.

**Comment by sellout** [comment]
To clarify – I only used it as an author – I _think_ the organizers liked it. I can ask.

**Comment by dwhitney** [comment]
Hey folks - just an update: looks like we're nearly set on a venue at the end of March. I haven't signed the contract yet because I want to get a quote on internet access to make sure it's not crazy expensive, but we're getting closer.

**Comment by larsrh** [comment]
Thanks, @dwhitney!

**Comment by larsrh** [comment]
[Announced](http://typelevel.org/event/2017-03-summit-nyc/)!
