### ISSUE TITLE
[Typelevel Summit Copenhagen, 2017] dates

### ISSUE THREAD

**Issue by larsrh** [typelevel/general#52]
We're currently in early planning stages for a possible Typelevel Summit in Copenhagen, happening before or after Scala Days. According to Trifork, the dates for Scala Days will be as follows:

* Training: Tue 30th, Wed 31st May
* Conference: Wed 31st – Fri 2nd

That leaves us with two sensible dates for the Summit: Mon 29st and Sat 3rd. Here are the trade-offs for Monday:

* easier to find a venue
* possible "gap" for attendees who don't wish to participate in the training sessions
* possibility for an unconference day the day after for interested participants

(Opposite for Saturday.)

Opinions?

**Comment by milessabin** [comment]
I think the gap after Monday is likely to be a problem for attendees who aren't participating in the Trifork training.

Selfishly a Saturday would work best for me.

**Comment by larsrh** [comment]
Assuming people are in for 2.5 days of Scala Days and 1 day of Typelevel Summit I'm pretty confident that the lack of an unconference day isn't a deal-breaker.

**Comment by larsrh** [comment]
Here's the result of [a poll](https://twitter.com/typelevel/status/811710150763368448) I ran on the @typelevel Twitter account:

     8% Directly before Scala Days
    33% Directly after Scala Days
    59% Either
    (63 votes)

**Comment by larsrh** [comment]
Quick update: I've contacted two different venues for the day after Scala Days. Will update again once I know more.

**Comment by larsrh** [comment]
Final date: June 3; [to be announced](http://typelevel.org/event/2017-06-summit-copenhagen/).
