### ISSUE TITLE
Submitting pureconfig for Typelevel incubator membership

### ISSUE THREAD

**Issue by melrief** [typelevel/general#55]
The [authors](https://github.com/melrief/pureconfig/blob/master/AUTHORS) of [pureconfig](https://github.com/melrief/pureconfig) would like to submit the library for Typelevel incubator membership.

The goal of the project is to provide "a boilerplate-free library for loading configuration files", which means (semi-)automatic derivation of writers and readers to/from configuration values. This is achieved by providing a layer on top of existing configuration libraries, like typesafe config.

Addressing the 4 point criteria:

1. there is consensus amongst the project's authors (@leifwickland, @jcazevedo, @ruippeixotog and I) about joining Typelevel.
2. we added the typelevel code of conduct with the [PR 107](https://github.com/melrief/pureconfig/pull/107) that has been accepted by all the members (@leifwickland and @jcazevedo approved the PR and @ruippeixotog wrote it on gitter). The code of conduct can be read by anybody via the [contribute](https://github.com/melrief/pureconfig#contribute) section of the project.
3. we are moving toward a more functional interface. <s>Currently most of the internal methods have no side-effects but the fact that we use `Try[A]` as return type of loading a configuration is not great. This will change with [issue 103](https://github.com/melrief/pureconfig/issues/103) that is schedules with high priority for the next release of pureconfig. After that, </s>we plan to add a nice functional API on top of Readers and Writers allowing to combine and transform them with [issue 93](https://github.com/melrief/pureconfig/issues/93)
4. `pureconfig` has a comprehensive [README](https://github.com/melrief/pureconfig/blob/master/README.md) covering most of the functionalities but there is much work to do. Specifically, <s>with [issue 102](https://github.com/melrief/pureconfig/issues/102) we want to move away from monolithic README to simplify its navigation and</s> with [issue 96](https://github.com/melrief/pureconfig/issues/96) we will move to `tut` to be sure that the examples in the doc really work.

**Comment by larsrh** [comment]
Cool stuff! Please have a look at e.g. #48 and clarify the following points:

1. There must be a consensus amongst the project's stakeholders that they want to join Typelevel.
2. The project must be willing to support the Typelevel code of conduct or something equivalent.
3. The project should be aiming to promote pure, typeful, idiomatic functional programming in Scala.
4. If the primary output of the project is software artefacts then it should aim to complement them with accessible, idiomatic documentation.

See also the [membership criteria](https://github.com/typelevel/general/blob/master/governance/membership.md#incubator-membership).

**Comment by melrief** [comment]
@larsrh thanks! I've updated the issue message with details about how pureconfig meets the membership criteria

**Comment by larsrh** [comment]
@melrief Welcome! Please add yourself to [the incubator](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml) by sending a PR. (And sorry for the long wait!)

**Comment by melrief** [comment]
Thanks @larsrh!
