### ISSUE TITLE
Typelevel membership for libisabelle

### ISSUE THREAD

**Issue by larsrh** [typelevel/general#56]
## Project description

[libisabelle](https://github.com/larsrh/libisabelle) is a library that talks to [Isabelle](http://isabelle.in.tum.de/). It offers a typed, RPC-style API to invoke operations on the Isabelle side, e.g. parsing formal terms, loading theories, and proving propositions. It also comes with a command-line interface to manage Isabelle installations and launch the theory editor with zero installation. It integrates with [coursier](https://github.com/alexarchambault/coursier) as a light-weight package manager for Isabelle theories.

## Membership criteria

1. I'm the only author.
2. See the [README](https://github.com/larsrh/libisabelle/blob/master/README.md#participation).
3. I'm depending on coursier, [monix](https://monix.io/), and [cats](http://typelevel.org/cats/) to provide a nice functional API. Future work: use [circe](https://github.com/circe/circe) for serialization and [iteratee](https://github.com/travisbrown/iteratee) for iteratees.
4. There is a lot of Scaladoc. Not complete, but decent. Also, an [example project](https://github.com/larsrh/libisabelle-example) and a [tut](https://github.com/tpolecat/tut)-checked [quickstart guide](http://lars.hupel.info/libisabelle/tutorial.html) are available.

**Comment by Atry** [comment]
Is it possible to create a macro implicit materializer, which search implicit type class via Isabelle?

**Comment by larsrh** [comment]
Possibly yes, but it would be rather complicated. The parts of Isabelle required for that are rarely used and I would expect a lot of problems lurking there.

**Comment by Atry** [comment]
Sigh... implicits searching is what I really hope Scala compiler would improve
