### ISSUE TITLE
Consider Extruder for Typelevel incubation

### ISSUE THREAD

**Issue by janstenpickle** [typelevel/general#57]
I would like to submit [Extruder](https://github.com/janstenpickle/extruder) for consideration as a Typelevel incubator project. This arose from my playing around with shapeless, it aims to do a similar thing as [Pureconfig](https://github.com/melrief/pureconfig), with a few [differences which are listed in the readme](https://github.com/janstenpickle/extruder#pureconfig).

With regard to membership criteria:

1. I am the only contributor
2. The Typelevel code of conduct is [present in the readme](https://github.com/janstenpickle/extruder#participation)
3. Uses Cats and Shapless extensively, all returned types are wrapped in `ValidationNel`
4. See the associated [readme](https://github.com/janstenpickle/extruder/blob/master/README.md)

**Comment by larsrh** [comment]
@janstenpickle Welcome! Please add yourself to [the incubator](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml) by sending a PR. (And sorry for the long wait!)

Pureconfig got also approved (#55) but I think a little competition can't hurt.

**Comment by larsrh** [comment]
On a more personal note: _adding the sixth Typesafe config wrapper to my bookmark list_. Those are the new JSON libraries, I'm calling it now :smile:

**Comment by janstenpickle** [comment]
@larsrh thanks very much, so happy it got accepted! 

So it looks like pureconfig, case-classy and extruder all do a very similar thing, hoping we might end up collaborating on some things.

**Comment by larsrh** [comment]
@janstenpickle Yes, that's the spirit of Typelevel!
