### ISSUE TITLE
Propose Hammock for Typelevel incubator

### ISSUE THREAD

**Issue by pepegar** [typelevel/general#59]
I would like to propose [Hammock](http://github.com/pepegar/hammock), a purely functional HTTP client for Scala, to the Typelevel incubator.

Regarding the criteria for submitting to the incubator:

1. I'm the only stakeholder of the project. Other people that was partially involved in it agreed and encouraged me to propose it.
2. There is a section in the [README](https://github.com/pepegar/hammock/blob/master/README.md#code-of-conduct) that states that people is expected to follow Typelevel CoC in this repository.
3. The project is currently based on Cats (also I'm planning cross compilation to Scalaz as well), and tries to be as functional as possible. For JSON encoding and decoding, provides `hammock-circe` packages, that make easy to use Circe encoders & decoders for HTTP. It also uses Monocle's optics for the high level API, Scalacheck & Discipline for law checking.
4. There is already a [documentation site](http://pepegar.com/hammock). All the docs are machine checked via tut.

**Comment by larsrh** [comment]
@pepegar Welcome! Please add yourself to [the incubator](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml) by sending a PR. (And sorry for the long wait!)

**Comment by pepegar** [comment]
Thank you @larsrh, feels great to be in finally :)

Here is [the PR](https://github.com/typelevel/typelevel.github.com/pull/156)
