### ISSUE TITLE
Typelevel membership for Frameless

### ISSUE THREAD

**Issue by adelbertc** [typelevel/general#6]
* Frameless is a library to provide a more typeful experience when working with Spark (SparkSQL specifically) with potential future plans to work with Algebra and Cats
* Frameless supports the Typelevel Code of Conduct

See: https://github.com/adelbertc/frameless

**Comment by milessabin** [comment]
:+1:

**Comment by InTheNow** [comment]
:+1: 

Double :+1: if Spark GraphX were to be included; but one :+1: is enough

**Comment by milessabin** [comment]
No objections so this is approved now too :-)

**Comment by larsrh** [comment]
Sorry for the delay. PR to add it to the website is pending: typelevel/typelevel.github.com#91.
