### ISSUE TITLE
Typelevel membership and code hosting  for sbt-tls-crossproject and catz-cradle

### ISSUE THREAD

**Issue by BennyHill** [typelevel/general#60]
@ShaneDelmore and I would like to propose sbt-tls-crossproject and catz-cradle for both Typelevel github hosting and for the Typelevel incubator. Both are new projects, but the underlying work with scalafix has been ongoing for some months.

- [sbt-tls-crossproject](https://github.com/BennyHill/sbt-tls-crossproject) adds TLS as a platform to [scala-native sbt-cross](https://github.com/scala-native/sbt-cross)
- [catz-cradle](https://github.com/BennyHill/catz-cradle) uses sbt-tls-crossproject and is the basis of  an example project to rewrite cats based code, initially to scalaz. This is currently achieved  by a fork of scalafix, the code there will be migrated to catz-cradle and eventually a new project, `catz`

We, the only two maintainers, would like to move the repos to TL ASAP, before we do the first releases.

Both projects and maintainers support the Typelevel CoC.

**Comment by larsrh** [comment]
Sorry for the long delay! I think we can approve this. (It seems like the move to the @typelevel org already happened?)

**Comment by larsrh** [comment]
Also, please send a PR to [the incubator](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml) so that it's listed on the website. /cc @ShaneDelmore
