### ISSUE TITLE
Full Membership for Monix

### ISSUE THREAD

**Issue by alexandru** [typelevel/general#61]
Hello,

Opening this ticket to request full membership for the [Monix](https://monix.io) project.

[It's been a year](https://github.com/typelevel/general/issues/4) since Monix has entered the Typelevel Incubator. 

About the criteria:

- the project evolved to exemplify functional programming and to protect users against using "hot" data source that are stateful - naturally some parts of the project are not FP (e.g. `monix-execution`), however those parts are separated and necessary, because Monix went ahead in expanding the standard library with the necessary low level primitives needed for concurrency handling; we also have [Cats integration](https://monix.io/docs/2x/intro/cats.html), along with [Scalaz](https://monix.io/docs/2x/intro/scalaz72.html), because the goal has always been to interact well with others within the ecosystem
- we have documentation type checked with `tut` at [monix.io/docs/2x/](https://monix.io/docs/2x/); more documentation is needed of course, will come in time, because it's highly technical and difficult to write; the last document I wrote for example has been on [MVar](https://monix.io/docs/2x/eval/mvar.html)
- we always had very complete [ScalaDocs](https://monix.io/api/2.2/) as well
- [versioning is semantic](http://semver.org/) and recently I integrated [MiMa](https://github.com/typesafehub/migration-manager) to help with that
- Monix has been my love child and I never stopped developing or maintaining it ever since its inception; it has one other part time maintainer as well and my pride is that the code in Monix is high-quality enough that people understand even highly challenging pieces, see [this recent bug report](https://github.com/monix/monix/issues/321) for example

Cheers,

**Comment by BennyHill** [comment]
I'm not sure what the actual rules/criteria for this are, but IMHO, Monix fulfills them. :+1:

**Comment by larsrh** [comment]
Seems like there is a lot of enthusiasm for this!

@alexandru, please file a PR to https://github.com/typelevel/typelevel.github.com/ moving this project from incubation to the full member list.

**Comment by alexandru** [comment]
Thanks @larsrh
