### ISSUE TITLE
Prioritize and collate sbt/scala/dbuild/community-build issues for community projects

### ISSUE THREAD

**Issue by BennyHill** [typelevel/general#62]
Scala Center Proposal: 

>I would like to propose that the Scala Centre (SC) maintain a community driven list of the open sbt/scala/dbuild/community-build issues that they would like priority given too. This could be as simple as a github driven list, but I would like to also suggest that the real value the SC could add is identifying issues that impact many projects and the general scala user experience, even if the individual issues themselves are not heavily voted for.
>
>Indeed, this could also progress to having "Meta Issues", groups of issues from many projects that on their own do not seem important for the individual projects, but are when viewed together, across projects. 
>
>Note that this does not stipulate that the SC actually do the work for the issues, but rather help focus issues that might otherwise get lost. By highlighting such, perhaps the community are motivated to do the work, perhaps some SC board members have Lightbend (LB) subscriptions and lobby other LB subscribers to vote for them. 

Specific examples to follow.

**Comment by BennyHill** [comment]
Examples, with my IMHO in []:

In the case of Typlelevel Scala (TLS), this is in fact already the case: the "FP" side of the community have identified the open issues of most interest to them and (@milessabin) set about fixing them. 

[Once the initial accolades subsided, there was a sense of "why didn't we do this earlier" and more people jumped on board to help out]

Examples of  issues that are are spread across projects include:
- Defining custom community builds (CB): 
  - Sharing configurations from other CB's
  - Getting shared configs via scaladex
  - Running then locally (via catalysts-docker)
  - Promoting these tools - if a project does not know a solution exists or is fit for a certain task, they will not use it. 
- Pattern matching vals in sbt
  - An old issue, advocated for fixing by many - see  https://github.com/sbt/sbt/issues/2290
https://github.com/sbt/sbt/issues/1661 - but perhaps not a high priortiy for business aligned projects
  - relates to "-Y rangepos" option in scalac. So the SBT fix also requires a scalac fix. 
  - The general issue here has also been a recurring issue in scoverage, probably the main test coverage tool for scala.
- Cross building projects:
  -  This is not a standard SBT feature [LB only have one compiler, LBS] 
  - Scala.js added cross project support for JVM/JS [They had no option]
  - scala-native has now taken this over, extending the Scala.js implementation. [They have no option, and as the complexity increases somewhat, they have made the interface slightly more generic]
  - TLS added its own platform type [The complexity is now such that a more generic interface is needed - why should the scala-native team do this?]
  - One method of implementing this is using  "Pattern matching vals in sbt"
  - Adding support of multiple version of libraries makes the current API almost unusable - who should be responsible for this? (How code is maintained for different library versions is a separate concern)
- Rewriting scala code to support multiple library versions, and other cross building tasks
  - scala-meta and scalafix can be leveraged, and are in [catz-cradle](https://github.com/BennyHill/catz-cradle)
  - custom community builds could test rewrites on existing projects, perhaps vis scaladex
  - Difficult to implement and test as SBT does not have full support for cross building....

**Comment by larsrh** [comment]
Thanks for the proposal! @BennyHill, do I have your permission to format & submit that as an official proposal for the next meeting (happening in a week)?

**Comment by BennyHill** [comment]
@larsrh  Sure - I'll whatever you want!!

**Comment by dwijnand** [comment]
Cross-linking. This is strongly related to #45.

**Comment by larsrh** [comment]
scalacenter/advisoryboard#20

**Comment by larsrh** [comment]
I think we should continue discussion & work out how to incorporate it into a proposal at scalacenter/advisoryboard#20.
