### ISSUE TITLE
Submitting Case Classy for Typelevel incubator membership

### ISSUE THREAD

**Issue by andyscott** [typelevel/general#63]
https://github.com/47deg/case-classy

Case classy is a tiny library to make it easy to decode untyped structured data into case class hierarchies of your choosing. It's completely modular, support Scala 2.11 and 2.12, ScalaJS ready, and the core module has zero external dependencies.

The project has been implemented in a functional manner from the beginning-- the core concept is a `Decoder[A, B]`, which is essentially a Kleisli arrow. The API is meant to be as simple as possible so that a FP background isn't required for beginner's to get started with it.

Out of the box there is support for Typesafe's Config for the JVM and Shocon for both JS/JVM. Support for any other input data source is also easy to assemble.

The framework meets all of the incubator status requirements. I am the project's primary maintainer, along with additional support from the rest of the 47 Degrees team.

Additionally, I believe the project meets all of the requirements for full membership sans the binary compatibility requirement. At the moment I aim for binary compatibility, but I don't expect perfect compatibility until a few in progress improvements are completed.

**Comment by andyscott** [comment]
Wanted to note that there is already a lot of documentation but I will be improving it to better highlight the broader use cases of the library (since it isn't just a wrapper for Typesafe Config).

**Comment by larsrh** [comment]
@andyscott Welcome! Please add yourself to [the incubator](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml) by sending a PR.
