### ISSUE TITLE
Submitting Libra for Typelevel incubator membership

### ISSUE THREAD

**Issue by zainab-ali** [typelevel/general#64]
[Libra](https://github.com/to-ithaca/libra) is a dimensional analysis library based on spire, shapeless and singleton-ops.
It fulfills the following criteria:
1. All maintainers (@zainab-ali and @yilinwei) want to join Typelevel
2. Libra [supports the Typelevel code of conduct](https://github.com/to-ithaca/libra/blob/master/CONTRIBUTING.md#code-of-conduct)
3.  Libra promotes functional programming through the use of spire and shapeless
4. Libra has [accessible machine-checked documentation](https://to-ithaca.github.io/libra/)

**Comment by non** [comment]
It seems like there is plenty of support, so shall we call it settled?

**Comment by larsrh** [comment]
Yes, welcome to Typelevel! Please send a PR to [add yourself](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml).
