### ISSUE TITLE
Submitting Paiges for Typelevel membership

### ISSUE THREAD

**Issue by non** [typelevel/general#70]
We're getting ready to publish Paiges and were hoping it would be considered as a Typelevel incubator project. Here's a link to the project:

https://github.com/johnynek/paiges

Basically, it's a way to pretty-print documents based on Wadler's *A Prettier Printer* paper, with a few novel extensions. It provides an immutable `Doc` type along with combinators to build up documents which can be rendered at different widths.

We haven't released yet and would love to put this in the `org.typelevel` namespace before our first release.

**Comment by non** [comment]
Follow-up details:

- The library is open-source (Apache 2)
- The library will be covered by the Typelevel CoC
- The library encourages functional programming
- The maintainers want the library to be in Typelevel (@johnynek can +1 to confirm this)

**Comment by johnynek** [comment]
+1 would be a dream come true.

**Comment by tpolecat** [comment]
I have been staring down a pretty-printer-shaped yak for a while now so this suits me just fine. 👍

**Comment by larsrh** [comment]
Sounds good to me! Do you want to move to the GitHub organisation or just use the group id for publishing?

**Comment by johnynek** [comment]
I'd rather do both, but definitely use the group id. If for some reason
moving has some issue I don't see.

What is the timeline for when we can publish? I'd like to publish soon.

**Comment by larsrh** [comment]
I'd be up for both too. On the phone right now, I'll post some instructions tomorrow. Timeline can be next week, I guess?

**Comment by larsrh** [comment]
1. Please post on [this issue](https://issues.sonatype.org/browse/OSSRH-4953), similarly to the previous requesters there.
2. I've invited you as a temp admin on the organisation so that you can transfer the repository here.

Welcome! 🎉

**Comment by johnynek** [comment]
@larsrh thanks! done:

https://github.com/typelevel/paiges

cc @non

**Comment by larsrh** [comment]
@johnynek OK, you're now admin of that repository and as such may add collaborators as you like. (@non has admin access to @typelevel, so you don't need to add him)

Final step: please send a pull request to [add the project to the website](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml).
