### ISSUE TITLE
eff full membership

### ISSUE THREAD

**Issue by etorreborre** [typelevel/general#73]
Hi @larsrh and all, I think now it could be time to make [`eff`](https://github.com/atnos-org/eff) a full member of Typelevel:

 - it is FP-like
 - it has [compiler-checked documentation](http://atnos-org.github.io/eff/) (I have used specs2 and not tut for this)
 - I am maintaining it actively (at least because I need it for work :-)) and @edmundnoble is also an active maintainer
 - there is a versioning scheme (but not enforced with MiMa yet)

**Comment by alexandru** [comment]
So the votes get counted with those emoji? I'm all for it and gave mine.

**Comment by larsrh** [comment]
Approved! Please move your project from the incubator to [projects](https://github.com/typelevel/typelevel.github.com/tree/development/_projects).

**Comment by etorreborre** [comment]
Thanks @larsrh I will move the project later on today.
