### ISSUE TITLE
Submitting mainecoon for Typelevel incubator membership

### ISSUE THREAD

**Issue by kailuowang** [typelevel/general#76]
[Mainecoon](https://github.com/kailuowang/mainecoon) is a library that helps to transform and compose tagless final encoded algebras. 

It fulfills the following criteria:

1. I am the sole maintainer right now and already a member of Typelevel
2. Mainecoon supports the Typelevel code of conduct in [readme](https://github.com/kailuowang/mainecoon#community)
3. Mainecoon promotes functional programming: it uses type classes with laws as building blocks; it uses cats' `FunctionK` as primitive for function; it uses cats' discipline in cats-law for testing infrastructure.
4. Mainecoon has [tut based documentation](http://kailuowang.com/mainecoon).

**Comment by larsrh** [comment]
I like the name :smile: Approved! Please add yourself to the [incubator](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml) list.
