### ISSUE TITLE
Submitting Ciris for incubator membership

### ISSUE THREAD

**Issue by vlovgr** [typelevel/general#77]
[Ciris](https://cir.is), as presented at the [Copenhagen Summit](http://typelevel.org/event/2017-06-summit-copenhagen/) ([slides](https://vlovgr.github.io/refined-types)), is a library for lightweight, extensible, and validated configuration loading in Scala and Scala.js.

1. I am the sole maintainer and developer at the moment.
2. Ciris supports the Typelevel Code of Conduct, as seen in the [Participation](https://cir.is/#participation) section.
3. Ciris promotes functional programming, relying on typeclasses for extensibility, and already integrates with several Typelevel projects (refined, shapeless, squants). Configuration loading is done with functional error accumulation similar to `ValidatedNel` with an `Apply` instance from Cats, except specifically generated with source generators to keep the core dependency-free.
4. Ciris has [tut-based documentation](https://cir.is/docs/basics) and [API docs](https://cir.is/api) (with sbt-doctest tests).

**Comment by larsrh** [comment]
Approved! Welcome & please add yourself to the [incubator](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml) list.
