### ISSUE TITLE
Typelevel membership for eff-cats

### ISSUE THREAD

**Issue by etorreborre** [typelevel/general#8]
The project is [here](http://github.com/etorreborre/eff-cats). It aims at bringing [extensible effects](http://okmij.org/ftp/Haskell/extensible) to Scala projects.

I still need to work on the tutorial (using tut which I haven't used before) and publish a 1.0.

**Comment by adelbertc** [comment]
:+1:

**Comment by milessabin** [comment]
Good stuff :-)

Could you add a mention of the Typelevel Code of Conduct to the README? Perhaps something along the lines of the [Contributing](https://github.com/non/cats#contributing) section of the Cats README.

**Comment by etorreborre** [comment]
Sure, I need to re-do the README anyway once the tutorial is finished. Is there anything else I should do?

**Comment by milessabin** [comment]
No, that should be sufficient to get the process started. See [here](https://github.com/typelevel/general/blob/master/governance/membership.md) ... we're at step (2).

**Comment by adelbertc** [comment]
(2) is satisfied: http://etorreborre.github.io/eff-cats/ , I'd say (3) is quite clearly satisfied :-) And (4) is also mostly, if not completely, satisfied by the website as well.

**Comment by milessabin** [comment]
Agreed ... :+1:

**Comment by etorreborre** [comment]
@milessabin if I can grab you one of these days I'd like you to review the implicit definitions I have been using to make all of this work. It has been a very frustrating process of trial and error to:

 - avoid putting type annotations in for comprehensions, when the result is `Eff[S, A]` where `S` is fixed
 - have effects with 2 type constructors being inferred, like `Reader[A, B]`
 - support the functionality of being able to run interpreters in any order, which is obtained by computing the list of effects which remains when one of them is removed

**Comment by larsrh** [comment]
Sorry for the delay. PR to add it to the website is pending: typelevel/typelevel.github.com#91.
