### ISSUE TITLE
Submitting decline for typelevel incubator membership

### ISSUE THREAD

**Issue by bkirwi** [typelevel/general#80]
I'd like to suggest [`decline`](https://github.com/bkirwi/decline/), a command-line parsing library, for Typelevel membership.

- I'm the sole maintainer. (With contributions from @tpolecat and @johnynek... thanks!)
- I haven't listed a CoC yet, but I'd be happy to adopt the Typelevel CoC.
- The library is written in, and encourages, a functional style.
- The library has `tut`-based documentation: http://monovore.com/decline/usage.html

**Comment by larsrh** [comment]
Welcome! Please add your project to the [incubator list](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml).
