### ISSUE TITLE
[Typelevel Summit Boston, 2018] Co-location with NE Scala

### ISSUE THREAD

**Issue by jducoeur** [typelevel/general#82]
We're starting to plan for NE Scala 2018 (in Boston this time); based on the success of the past two, we are tentatively assuming that the TL Summit will be connected to that again, and we're scheduling a day for that.

I'm co-organizer for NE Scala this year, so I can serve as a contact there.  It would be helpful if somebody could take point on the TL side, so I've got a clear contact to work with.

The immediate priority is confirming that Typelevel collectively wants to do this again.  We're working with a site, and while we can't promise anything, we *hope* to be able to reserve an extra day for the Summit, and so far the signs look good.  If TL isn't interested, though, we need to know ASAP.

After that, we should coordinate the messaging, and plan out how both groups will be choosing their agendas, so that we don't step on each other.

We are *not* expecting much in terms of logistical help from TL -- knock on wood, we hopefully have that part under control.  (We will be looking for sponsors, and welcome contacts there, but that's presumably not so much about TL per se.)

**Comment by larsrh** [comment]
I think last year's US edition of the Typelevel Summit worked really well. If you're onboard with that model, then I'm happy to help and serve as point of contact. Let's keep this open for a couple of days to see what people think.

**Comment by jducoeur** [comment]
Okay, sounds good.  I agree that it seemed to go quite well, and I'd like to keep the momentum going...

**Comment by larsrh** [comment]
How are the plans progressing? Is there already a rough date?

**Comment by jducoeur** [comment]
Sorry -- yes.  Not much aside from dates yet, but we do have dates.  It's going to be March 18 - 20, 2018.  Note that that's Sun-Tues: a change from previous years, but it was what worked best for the site in our general time range, and conversations on scala/scala didn't turn up any major objections.  The site is the Broad Institute in Cambridge, MA.

We have *not* yet decided which of the three events (TL Summit, NE Scala, Unconference) will be on which day; if folks from TL have particular opinions, we'd love to hear them.

**Comment by larsrh** [comment]
I personally prefer the same sequence as last year (Summit, NE Scala, Unconf) because most people who go to the Summit will also want to go to NE Scala, but not vice versa.

**Comment by larsrh** [comment]
But I also just posted this on our Gitter channel, so let's see who has opinions :smile:

**Comment by longcao** [comment]
FYI - March 18-20th, 2018 will overlap with ScalaMatsuri

http://2018.scalamatsuri.org/en/cfp/

**Comment by jducoeur** [comment]
Hmm.  That's unfortunate, but probably not much we can do about it now --
the site is reserved.  (When we asked around about this date, nobody
mentioned this conflict.)

**Comment by longcao** [comment]
I thought it was worth mentioning anyways, it seems like trying to plan around a conference conflict halfway around the world isn't worthwhile 😄

**Comment by jducoeur** [comment]
True enough.  But good to know about the conflict -- thanks...

**Comment by SethTisue** [comment]
@jducoeur if the NE Scala dates are now fixed, a PR adding them to http://scala-lang.org/events/ would be welcome — Scala Matsuri is already listed there
