### ISSUE TITLE
Typelevel representative at the Scala Center Advisory Board, 2nd term

### ISSUE THREAD

**Issue by larsrh** [typelevel/general#83]
Because of typelevel/general#42, I've served one year as the Typelevel representative at the Scala Center Advisory Board.

During that time, I have written one proposal ([sbt migration](https://github.com/scalacenter/advisoryboard/blob/master/proposals/013-sbt-migration.md)) and sponsored one proposal ([debugging symbols](https://github.com/scalacenter/advisoryboard/blob/master/proposals/011-debugging-symbols.md)), both of which got accepted. (To clarify: IIRC all proposals put forth got accepted so far.)

This is the time to discuss about a possible successor of my seat. Feel free to nominate someone in this thread, or re-nominate me. Note that the Advisory Board needs to confirm a successor. Please just one nomination per comment, and use :+1: for voting. There's no particular rush.

**Comment by milessabin** [comment]
I nominate @larsrh to continue as the Typelevel representative.

**Comment by larsrh** [comment]
I propose to keep this open for a couple more days (let's say Wednesday, Oct 4th). If nobody suggests anything else, I'll assume that the status quo continues.

**Comment by larsrh** [comment]
Thank you!
