### ISSUE TITLE
Move Mouse to under typelevel org

### ISSUE THREAD

**Issue by kailuowang** [typelevel/general#84]
Per discussion [here](https://github.com/benhutchison/mouse/issues/29), it would make more sense for Mouse, an external cats module, to be moved into the typelevel github org as well as publish under `org.typelevel`

WDYT?

**Comment by larsrh** [comment]
Sounds good! @benhutchison, I've invited you to the @typelevel org so you can transfer the repository.

**Comment by benhutchison** [comment]
Repo transferred. I'll republish a jar under the typelevel maven id, see PR. How do the publishing credentials work?

**Comment by larsrh** [comment]
Add a comment to [this ticket](https://issues.sonatype.org/browse/OSSRH-4953) and your Sonatype credentials will get access to `org.typelevel`.
