### ISSUE TITLE
Submitting OutWatch for typelevel incubator membership

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/general#85]
I'd like to propose [OutWatch](https://github.com/OutWatch/outwatch) as a Typelevel incubator project. OutWatch is a lightweight library for programming UIs with Scala.js. 

1. Me and the only other maintainer Felix, have agreed that this is a good idea.
2. There's currently no CoC in place, but I fully support the TL CoC and would love to adopt it.
3. OutWatch aims to be fully functional and typesafe, there's a few exceptions currently, but I've already drafted a fully working version that is fully referentially transparent. Only need to update the documentation.
4. There's already a whole website focusing on documentation for OutWatch, and I'm currently rewriting a lot of the documentation in `tut`.

**Comment by larsrh** [comment]
Welcome! Please add your project to the [incubator list](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml).
