### ISSUE TITLE
[Typelevel Summit Berlin, 2018] dates

### ISSUE THREAD

**Issue by larsrh** [typelevel/general#86]
2018's European edition of Scala Days will happen in Berlin: https://eu.scaladays.org/

* 14-15 May: Workshops
* 15-17 May: Conference Sessions

We are considering holding a Typelevel Summit directly after Scala Days, on Friday, 18 May.

We're currently looking for:
* comments on the date
* suggestions for a venue

**Comment by larsrh** [comment]
I've created a poll here: https://twitter.com/typelevel/status/932969039076429824

**Comment by propensive** [comment]
You should ask Zalando whether they could host it. I can put you in touch with someone who may be able to help.

**Comment by milessabin** [comment]
Zalando would be a great venue. I think Lauri Apple (@LauritaApplez) would be the person to talk to.

**Comment by larsrh** [comment]
Thanks, Miles, Jon – I've already approached Zalondo and expect to hear back shortly.

**Comment by larsrh** [comment]
Seems like nobody has anything against the date, so finding a venue for May 18 is our focus at this point. I/We are in contact with multiple prospective venues and/or hosts.

**Comment by quiquedeveloper** [comment]
i dont know how much place you need but you can check these two: 
https://www.urania.de/en/urania-berlin
https://www.kosmos-berlin.de/

**Comment by propensive** [comment]
Thanks, @quiquedeveloper. I think @larsrh has found a venue now, right?

**Comment by larsrh** [comment]
typelevel/typelevel.github.com#198
