### ISSUE TITLE
Proposal: Small & focussed Type Tag library

### ISSUE THREAD

**Issue by benhutchison** [typelevel/general#87]
I use Type Tags myself pretty often... I've used the Shapeless implementation at time, but in other projects, which don't otherwise depend on Shapeless, Ive defined them myself from scratch.

On several occasions in the last two years, Ive seen interest in a type-tag focussed library, eg:
- [Cats Gitter May 16](https://gitter.im/typelevel/cats?at=56d9f70ab0cc3f1b415024fd)
- [Cats Gitter June 16](https://gitter.im/typelevel/cats?at=575b2a1e6092456f663308e3)
- [Cats issue 425](https://github.com/typelevel/cats/issues/425#issuecomment-222505614)

I want to propose (and I offer to maintain) a small typelevel lib that probably provides just 2 operations:
- [Subtype tagging](https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/typeoperators.scala#L25)
- [Newtype tagging](https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/typeoperators.scala#L36)

This isn't about defining new functionality or supporting advanced tagging use-cases, rather standardising operations people are already doing into a lightweight lib. As such, buy-in from typelevel user community would be important to project success.

Hence Im testing interest in the idea..?

**Comment by larsrh** [comment]
What about @julien-truffaut's newts library? https://github.com/julien-truffaut/newts

**Comment by benhutchison** [comment]
I wasn't aware of newts actually. That seems to address much of what I had
in mind.

There are use cases where subtype tags are needed, eg attaching additional
info to Array[Double] without losing the underlying type. I didn't see
support for that in newts?

-Ben

**Comment by benhutchison** [comment]
Also (belatedly!) just noticed discussion at https://github.com/typelevel/cats/issues/1800 that seemed to reach leaving tags outside cats as at 1.0
