### ISSUE TITLE
Graduate cats-effect out of Incubator

### ISSUE THREAD

**Issue by alexandru** [typelevel/general#88]
Hi all,

[Cats-effect](https://github.com/typelevel/cats-effect) is in the incubator phase right now and I think it's time for it to be listed as a project with full membership.

- several high profile libraries in the ecosystem already depend on it: Doobie, Fs2, Monix, Http4s, etc
- exemplifies FP, typeful programming
- ScalaDoc is in good shape, we plan to release a tut-checked microwebsite tomorrow with the 0.10 release
- development is very active and pretty well maintained (imo)

**Comment by larsrh** [comment]
Approved! Please move your project from the incubator to [projects](https://github.com/typelevel/typelevel.github.com/tree/development/_projects).
