### ISSUE TITLE
Submitting scala-steward for incubator membership

### ISSUE THREAD

**Issue by fthomas** [typelevel/general#91]
I'd like to propose [scala-steward](https://github.com/fthomas/scala-steward) as a Typelevel incubator project. scala-steward is a program that updates libraries and plugins of Scala projects on GitHub. I'm running one instance of scala-steward on my own server as a free service for the whole Scala open source community.

1. I'm the sole maintainer
2. scala-steward supports the Scala Code of Conduct
3. scala-steward is a purely functional program built on top of many other Typelevel libraries
4. Currently there is not much documentation, but I'm committed to adding more

**Comment by larsrh** [comment]
Approved! @fthomas, please add the project to the website; you know the drill :wink:
