### ISSUE TITLE
Submitting Jawn for Typelevel membership

### ISSUE THREAD

**Issue by travisbrown** [typelevel/general#92]
This proposal is a follow-up to discussion in [this Jawn issue](https://github.com/non/jawn/issues/126). As @larsrh notes there, Jawn seems to meet the [requirements](https://github.com/typelevel/general/issues/5) for Typelevel membership. I don't personally feel strongly about whether Jawn should join as a Typelevel incubator project or as a full member, but given its maturity and level of adoption it seems reasonable to me to have it start with full membership.

While this proposal is being considered, I can go ahead and open a Jawn PR changing the package to `org.typelevel.jawn` and updating links, documentation, and artifact coordinates. Once it's approved, we'll just need to move the repository from `non/jawn` to `typelevel/jawn` (we could fork but it'd be nice to bring over issues, PRs, tags, etc. automatically) and publish a new release (ideally with Scala 2.13.0-M5 artifacts).

r? @non @larsrh @milessabin

**Comment by larsrh** [comment]
I forgot one thing: Jawn currently does not have a CoC in it. But if it gets transferred to the Typelevel organization, it would be covered by our global one (unless, of course, we decide to pick the Scala CoC instead).

**Comment by larsrh** [comment]
Overwhelming support. Approved!
