### ISSUE TITLE
Submitting cron4s for incubator membership

### ISSUE THREAD

**Issue by alonsodomin** [typelevel/general#97]
The authors (well, me) of [cron4s](http://github.com/alonsodomin/cron4s) would like to submit the library for Typelevel Incubator membership.

The goal of the library is to provide a typesafe, cross-platform CRON expression parser for Scala. The library itself is implemented using many the fundamentals of FP, has pluggable modules that integrate it with other Typelevel projects (some of them created by the community).

Addressing the 4 points of the membership criteria:
* There is a consensus between authors (it's just me) on joining Typelevel.
* `cron4s` uses Scala's CoC, which is compatible with Typelevel's CoC.
* It is referential transparent: does not throw exceptions (with the _exception_ of the `Cron.unsafeParse` method) but it returns monadic types that signal the fact that an error has occurred and calculating the next time to given one using the same expression, always returns the same value. It is also typeful, the elements in the CRON AST are paremeterized by the position they are in to minimize the chances of building wrong expressions.
* It is well documented in https://alonsodomin.github.io/cron4s

**Comment by alexandru** [comment]
Hey, just noticed this — looks pretty cool.

Quick question — can your cron data structure do unions and intersections?

**Comment by alonsodomin** [comment]
Glad you find it interesting.

Not sure what you mean in your last question... is it the possibility of combining two cron expressions into one? in such a case no, that isn't supported and I think it'd be quite complicated to implement.

As it stands now, it's just a parser of cron textual expressions into an ADT with a handful of operations on date time structures.

I'd like to rewrite part of its internals after the 2.13 release is complete to make the library simpler, any ideas on missing features are of course welcomed.

**Comment by SethTisue** [comment]
did this get forgotten about?

**Comment by larsrh** [comment]
Indeed, thanks @SethTisue for the reminder and sorry @alonsodomin! Somehow this fell through the cracks.

Incubator membership is approved. Please send a PR to https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml to add your project.
