### ISSUE TITLE
Submitting decline for full membership

### ISSUE THREAD

**Issue by bkirwi** [typelevel/general#99]
Hi!

I'm the maintainer of [decline](https://github.com/bkirwi/decline), which was added to the incubator [a couple years ago](https://github.com/typelevel/general/issues/80). The library has remained very stable, had a 1.0 release recently, and overall IMO has been a good member of the ecosystem. Would y'all consider it for full membership?

**Comment by tpolecat** [comment]
💯 enthusiastically endorse

**Comment by milessabin** [comment]
Seconded!

**Comment by larsrh** [comment]
Approved! :tada: @bkirwi, please file the appropriate PRs on the website and we can finish this up.
